### ISSUE TITLE
Add missing documentation for several project settings properties.

### ISSUE THREAD

**Issue by Ybaedbaenn** [godotengine/godot-docs#5372] opened 2021-11-05 20:36 UTC
**Your Godot version:**
 3.3.4.stable.official

**Issue description:**
The following project settings properties are available in the editor, but have no description in the editor or in the documentation page for ProjectSettings:
application/config/auto_accept_quit
application/config/quit_on_go_back
application/run/main_loop_type
audio/mix_rate.web    - has description in the editor, but not in the documentation
display/window/stretch/aspect
display/window/stretch/mode
display/window/stretch/shrink
editor/convert_text_resources_to_binary_on_export
editor/main_run_args
editor/reimport_missing_imported_files
gui/common/snap_controls_to_pixels
gui/common/text_edit_undo_stack_max_size    - exists in the documentation, but has no description, only a name
filesystem/import/fbx/use_fbx
memory/limits/command_queue/multithreading_queue_size_kb - exists in the documentation, but has no description, only a name
rendering/quality/dynamic_fonts/use_oversampling

Additionaly the following project settings appears in editor (and are not documented), when an AutoLoad script named Global is set up:
autoload/Global
Global/back
Global/backgr

There is no documentation on the ProjectSettings docs page for these project settings tabs available in the editor:
Localization, AutoLoad, Plugins, Import Defaults, GDNative.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/classes/class_projectsettings.html

**Comment by Calinou** [comment] 2021-11-05 22:43
Duplicate of https://github.com/godotengine/godot/issues/42481 (same cause).
These project settings aren't documented because they're not discovered by `--doctool`. To make them discovered by `--doctool`, the engine code needs to be modified.

< Additionaly the following project settings appears in editor (and are not documented), when an AutoLoad script named Global is set up:
autoload/Global
Global/back
Global/backgr

**Closed** 2021-11-05 22:44 UTC
Labels: archived, enhancement
