### ISSUE TITLE
C++ missing from documentation

### ISSUE THREAD

**Issue by baptx** [godotengine/godot-docs#1187] opened 2018-02-28 20:36 UTC
C++ is missing from this documentation page:
https://godot.readthedocs.io/en/3.0/getting_started/scripting/index.html

But it should be listed according to this documentation page:
https://godot.readthedocs.io/en/3.0/about/faq.html#which-languages-are-supported-in-godot

> The officially supported languages for Godot are GDScript, Visual Scripting, C# and C++. See the subcategories for each language in the scripting section.

I was told to report this here (https://twitter.com/_eons/status/968891021848432640).

**Comment by mhilbrunner** [comment] 2018-03-01 00:28
Duplicate of https://github.com/godotengine/godot-docs/issues/140

**Closed by mhilbrunner** 2018-03-01 00:28 UTC
