### ISSUE TITLE
Outdated Godot Architecture Diagram

### ISSUE THREAD

**Issue by Lege19** [godotengine/godot-docs#9500] opened 2024-06-17 18:57 UTC
**Your Godot version: Godot 4**

**Issue description: The diagram shown is very outdated**

**URL to the documentation page: https://docs.godotengine.org/en/stable/contributing/development/core_and_modules/godot_architecture_diagram.html**

I've specifically noticed that this diagram contains:

- Spatial2DSoundServer
- Spatial3DSoundServer (For these two I have found direct documentation and no references newer than Godot 2.1
- Physics2DServer (From Godot 3, replaced by PhysicsServer2D in Godot 4)
- PhysicsServer (Also from Godot 3, replaced by PhysicsServer3D in Godot 4)
- VisualServer (Also from Godot 3, replaced by RenderingServer in Godot 

This merely serves to demonstrate that the diagram is outdated, I expect it will need to be completely replaced as it looks like it may not have been changed since Godot 2.

**Comment by skyace65** [comment] 2024-06-17 23:37
Closing as a duplicate of #9265.

**Closed by skyace65** 2024-06-17 23:37 UTC
Labels: bug
