### ISSUE TITLE
GraphEdit connection dictionary keys appear incorrect in get_connection_list()

### ISSUE THREAD

**Issue by Go-Ba** [godotengine/godot-docs#8956] opened 2024-02-14 03:05 UTC
**Your Godot version:**
v4.2.1.stable.mono.official [b09f793f5]

**Issue description:**
keys listed in the documentation appear to be incorrect

stated:
> Returns an Array containing the list of connections. A connection consists in a structure of the form `{ from_port: 0, from: "GraphNode name 0", to_port: 1, to: "GraphNode name 1" }`.

But the `from` and `to` don't work.
When printing the keys I get
![image](https://github.com/godotengine/godot-docs/assets/64071930/739e44b5-0d7d-4bbb-bb79-18472abfec6c)

so I presume it should be `{ from_port: 0, from_node: "GraphNode name 0", to_port: 1, to_node: "GraphNode name 1" }` instead.

I am working in C#, I am not sure if this makes a difference.

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/classes/class_graphedit.html#class-graphedit-method-get-connection-list

**Comment by AThousandShips** [comment] 2024-02-14 16:37
Duplicate of https://github.com/godotengine/godot-docs/issues/8625

**Closed by AThousandShips** 2024-02-14 16:37 UTC
Labels: bug
