### ISSUE TITLE
Add an email submission form to docs (and editor)

### ISSUE THREAD

**Issue by willnationsdev** [godotengine/godot-docs#2233] opened 2019-03-07 00:02 UTC
Many users that I have conversed with do not report the problems they encounter while reading the documentation. I believe this is in part because the accessibility of reporting errors is overly complex for users.

I think it should be possible to modify our usage of the Read The Docs Sphinx theme to add a widget (say, in the bottom right), that uses JavaScript to open an email in someone's local email client. We could have the email go to a godotengine.org URL and include detailed information about a suggested change to the docs or class API docs.

Suggested values to insert into subject and/or body:

1. URL for web page
2. Reproduction of selected text in web browser
3. An empty field for [name]
4. An empty field for [problem description]
5. An empty field for [proposed solution]

This would then make it *very easy* for people reading the documentation to report on suggested changes and help streamline the exact lines on any given page that the docs team has been asked to address.

- No need for readers to have a GitHub account.
- No need for readers to be redirected to another site.
- Readers can report on confusing or incorrect content the moment they observe a problem without greatly breaking the flow of their reading.

An ideal solution (in my mind) would be for a modal to pop-up and allow them to submit the email via ajax to godotengine servers (no need for an email client to open up).

I saw examples of this kind of thing in action [here](https://stackoverflow.com/questions/7381150/how-to-send-an-email-from-javascript) (includes both email client and 3rd party API versions).

With such detailed suggestions like this, it would be simple for a contributor with access to the email to fix several things in a small amount of time. Or, perhaps a job reproduces godot-docs Issues from the received emails? Idk.

Anyway, does something of this sort (or a similarly user-friendly model) sound like a good idea? If not, does anyone have any suggested alternatives?

**Comment by bojidar-bg** [comment] 2019-03-08 12:25
Duplicate of #323?

**Comment by willnationsdev** [comment] 2019-03-12 12:00
@bojidar-bg oh, indeed. Closing. Thanks!

**Closed** 2019-03-12 12:00 UTC
