### ISSUE TITLE
Dodge the creeps is helpful but outdated and no longer works completely

### ISSUE THREAD

**Issue by DanielMcGuffey** [godotengine/godot-docs#7022] opened 2023-03-19 22:08 UTC
4.0

I followed the dodge the creeps tutorial as someone completely new to coding and game dev. It was helpful only to a point. I finished coding player movement and did the rest of the code and it ran but nothing showed up no HUD or Mobs or even the player. When I was coding it there were some things that were outdated and no longer worked but most were not a very big deal. Except for the signals. I could make new signals but the emit code was null  so didn't work I tried to rig something together. I am assuming the reason the game didn't start was because it didn't emit or call the new_game signal but, that is just a guess please update the tutorial so it doesn't have this  problem in the future or add a warning saying "this is outdated and doesn't work except for player movement."

thank you for everything but please try fixing the problem.

https://docs.godotengine.org/en/stable/getting_started/first_2d_game/index.html

**Comment by MisoMosiSpy** [comment] 2023-03-22 21:43
I went though this tutorial:

**Using GDScript:** The tutorial is almost correct (except for the signals and some minor errors), I was able to finish and run the game. 

**Using C#:**  There are quite a few issues, I am working on PR to fix them. 

If you tried with GDScript what kind of issues are you facing?

**Comment by DanielMcGuffey** [comment] 2023-03-23 02:01
I coded it in GDScript and after coding the player once I wrote hide() the
player never showed up again so I just assumed it was due to the signals
because they were causing errors. I have never coded before (except on
scratch) and so didn't know how to fix it thank you for noticing my
complaint so if you could just try to fix errors on GDScript as well as C#.

**Comment by MisoMosiSpy** [comment] 2023-03-23 07:49
OK, thanks for the info!

**Comment by DanielMcGuffey** [comment] 2023-03-23 11:14
No problem!

**Comment by mj-h** [comment] 2023-03-23 23:17
I was stuck in the 2d tutorial [here](https://github.com/godotengine/godot-docs/blob/e22128ca06e923d58be3eebe9a0fa01b0d4e2c9f/getting_started/first_2d_game/05.the_main_game_scene.rst?plain=1#L185). I think there is a step missing: The user has to add (drag/drop) the "Player" scene to the "Main" scene.

**Comment by MisoMosiSpy** [comment] 2023-03-24 06:35
Line 12, in the same file explains the step to add Player instance in Main
scene.

**Comment by lancemgiles** [comment] 2023-03-28 01:44
I had a similar issue as Daniel, but after finishing "the main game scene" section, the player became visible again. I don't think this is actually a bug but it would likely be helpful to new people to point out that the game won't really be testable again from the end of the the player section until the end of the main section. At least, that is what I thought was going on.

For me, the player does not get hidden when colliding with the mob - searching for information about that is what lead me to this thread. I'm not sure if this is problem on my end or not.

**Comment by Creidhne86** [comment] 2023-04-02 03:33
I'm stuck on the OnBodyEntered() part of the "Coding the player" section. I'm using C#. 

Its a bit odd, because I'm connecting the signal, but getting an error as soon as I try and build the code that Godot imports.. 

Errors I'm getting:
...\2d_Game_Dodge_Creeps\player.cs(76,1): Top-level statements must precede namespace and type declarations.
...\2d_Game_Dodge_Creeps\player.cs(76,1): The modifier 'private' is not valid for this item

line 76 is this: private void _on_body_entered(Node2D body)

**Comment by MisoMosiSpy** [comment] 2023-04-02 11:33
You need to move the signal handler inside the player class (just move it
before the last '}').

This is known issue in godot c#.

**Comment by raulsntos** [comment] 2023-04-02 12:38
- For reference, the issue is being tracked in https://github.com/godotengine/godot/issues/18721.

I've recently seen some people get confused about this, so I think it would be nice to add a note in the tutorial about this until the bug is fixed.

**Comment by immortius** [comment] 2023-09-16 12:31
> For me, the player does not get hidden when colliding with the mob - searching for information about that is what lead me to this thread. I'm not sure if this is problem on my end or not.

Working through the tutorial now, at the end of the Coding the Player page you are instructed to create a start() function that enables player collision, but you are never instructed to call this method later in the tutorial (presumably should be part of the Main script, called when the game starts).

**Comment by AThousandShips** [comment] 2023-09-16 12:48
That doesn't hide anything, the hide code is three lines above, the "disabled" just disables the collision shape so it doesn't collide any more, it isn't drawn anyway

**Comment by immortius** [comment] 2023-09-16 14:39
You misunderstand. This is the code to enable the collision for the player on start. It doesn't work, so when the mobs should hit the player they pass straight through and never trigger the hiding of the player.

**Comment by fvarga01** [comment] 2023-10-02 00:14
Dodge the creeps utorial is stil broken when trying this on 4.1.1, various pieces out of date, had to do web searches to determine things have been changes or renamed in 4.0 . For example: 1- Use Marker2D type instead of Position2D . Is this tutorial being updated soon for 4.0?

**Comment by Piralein** [comment] 2024-08-25 13:16
The "Getting Started 2D Section" received multiple bugfix and enhancement PR's since this issue was opened.
As there is no concrete problem mentioned, (except the c# issue, which is tracked in other issues) I will close this issue for now.
If you still have a problem with the tutorial please open a new issue with a detailed description of the problem.

Please feel free to ask for help in any of the offical [Community Channels](https://godotengine.org/community/) if you are stuck at any point of the tutorial.

**Closed by Piralein** 2024-08-25 13:16 UTC
Labels: bug, area:getting started
