### ISSUE TITLE
No such method as Control._input_event(ev)

### ISSUE THREAD

**Issue by timcode77** [godotengine/godot-docs#5291] opened 2021-10-02 03:38 UTC
**Your Godot version:**
v3.3.3.stable.official [b973f997f]

**Issue description:**
Image in docs refers to "Control._input_event(ev)" but there is no method with that name. I think it should be Control._gui_event(ev).

The image in question is here::
https://docs.godotengine.org/en/stable/_images/input_event_flow.png

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/tutorials/inputs/inputevent.html

**Comment by Calinou** [comment] 2021-10-02 15:00
Duplicate of https://github.com/godotengine/godot-docs/issues/2619.

**Closed by Calinou** 2021-10-02 15:00 UTC
Labels: bug
