### ISSUE TITLE
Outdated info godot 4 (multiplater ENet)

### ISSUE THREAD

**Issue by pc9098** [godotengine/godot-docs#6741] opened 2023-02-07 00:39 UTC
https://docs.godotengine.org/en/latest/tutorials/networking/high_level_multiplayer.html

See that it is in latest, which should be Beta 4.17

-Initializing the Network:
It uses classes like NetworkedMultiplayerENet that have been changed.

**Comment by pgorley** [comment] 2023-03-08 02:34
I'd like to bump this issue since the page is terribly broken.  It suggests using a class that doesn't exist and there's no path forward for people previously using ENetMultiplayerPeer in 3.5.  ENetMultiplayerPeer is also completely different and I assume it's no longer supposed to even be around in 4.0.  If I knew a path forward (which APIs I can call), I'd be glad to contribute here, but I'm just as lost as the current documentation.

**Comment by TristanTurcotte** [comment] 2023-03-11 02:47
> I'd like to bump this issue since the page is terribly broken. It suggests using a class that doesn't exist and there's no path forward for people previously using ENetMultiplayerPeer in 3.5. ENetMultiplayerPeer is also completely different and I assume it's no longer supposed to even be around in 4.0. If I knew a path forward (which APIs I can call), I'd be glad to contribute here, but I'm just as lost as the current documentation.

You may find the article [Multiplayer in Godot 4.0: ENet wrappers, WebRTC](https://godotengine.org/article/multiplayer-changes-godot-4-0-report-3/) helpful. That entire series of blog posts (except for the 4th one) contain some good information about the changes

**Comment by mhilbrunner** [comment] 2023-03-31 22:47
Closing as duplicate of https://github.com/godotengine/godot-docs/issues/5755 and https://github.com/godotengine/godot-docs/issues/5754

FYI, the multiplayer docs are in the process of being reworked. Until then, have a look at the [Bomberman](https://github.com/godotengine/godot-demo-projects/tree/master/networking/multiplayer_bomber) and [TPS](https://github.com/godotengine/tps-demo/tree/4.0-dev) demos to see how the new multiplayer features in Godot 4.0 can be used.

**Closed by mhilbrunner** 2023-03-31 22:47 UTC
Labels: bug, area:manual

**Comment by MisterE123** [comment] 2024-01-07 01:20
This is very important. I really wish that the multiplayer docs were current ... and if they are, I would like to know

**Comment by MisterE123** [comment] 2024-01-07 01:21
Oh it was closed as completed ... so I guess that the checkbox on https://github.com/godotengine/godot-docs/issues/5121 should be marked...

**Comment by pc9098** [comment] 2024-01-07 02:38
> Oh it was closed as completed ... so I guess that the checkbox on #5121 should be marked...

This was closed as duplicate, not as completed.
I suggest you these videos they are a good start:
[](https://youtube.com/playlist?list=PLRdlA0DoNf6_vWj7grJETu-m0HfUQV94L&si=dxvAU7aVSNq9U6y4)
