### ISSUE TITLE
Words are over-translated

### ISSUE THREAD

**Issue by shiena** [godotengine/godot-docs#9186] opened 2024-04-05 11:34 UTC
For example, some keywords in GDScript should not be translated, but have been translated in several languages.
Is there any way to prevent such over-translation?

en: https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_basics.html#keywords

ja: https://docs.godotengine.org/ja/4.x/tutorials/scripting/gdscript/gdscript_basics.html#keywords
<img width="537" alt="スクリーンショット 2024-04-05 20 29 47" src="https://github.com/godotengine/godot-docs/assets/1295639/6490b5bc-a6f9-443c-82b7-8d080ffda80c">

ru: https://docs.godotengine.org/ru/4.x/tutorials/scripting/gdscript/gdscript_basics.html#keywords
<img width="537" alt="スクリーンショット 2024-04-05 20 33 11" src="https://github.com/godotengine/godot-docs/assets/1295639/491be3f7-1b28-4371-a22c-06f1ce715e03">

**Comment by skyace65** [comment] 2024-04-08 01:12
Closing as a duplicate of #8890.

**Closed by skyace65** 2024-04-08 01:12 UTC
Labels: bug

**Comment by Cerno-b** [comment] 2024-05-08 21:55
@shiena If this is about keywords being translated even though a translation makes no sense, I fear there is currently no way to prevent this. You could add a word to Weblate's glossary and mark it as *forbidden*, but in my opinion it would only needlessly fill the glossary with bloat and make it unusable.

I think this is only tangentially related to #8890 because that ticket is meant for recurring terminology and not keywords, I think it may make sense to extend the ticket to have a role for keywords as well, which should not appear in Weblate at all.

In the example you gave, I think it's mainly the translators' responsibility to recognise the overtranslation and to fix them. In one instance, this is not only a translation where there shouldn't be one, but instead it is incorrectly translated *pass* is translated as レンダーパス (render pass).
