### ISSUE TITLE
Duplicate results in docs search popup

### ISSUE THREAD

**Issue by SylvanSign** [godotengine/godot-docs#5650] opened 2022-02-26 02:02 UTC
**Your Godot version:**
stable (3.4)
**Issue description:**
duplicate search results in docs. Seems to always show exactly 2 identical hits for each relevant page
**URL to the documentation page:**
Example showing duplicate results https://docs.godotengine.org/en/stable/classes/class_string.html?rtd_search=pckpacker
![image](https://user-images.githubusercontent.com/18179992/155824668-b7c1c60d-856c-43ed-81cd-60ae41f87f42.png)

**Comment by akien-mga** [comment] 2022-03-09 10:31
The issue is reproducible on `3.4` and `stable`, but not on `3.3`: https://docs.godotengine.org/en/3.3/classes/class_string.html?rtd_search=pckpacker

So it's likely a regression from updating the `readthedocs-sphinx-search` extension two weeks ago: 6001b2400064008ff08ebed3059a83d2ba18617b

I'll check if the latest upstream commit helps: https://github.com/readthedocs/readthedocs-sphinx-search/commits/master
It seems like it might also finally lift the limitation we have that prevented us from upgrading Sphinx due to incompatibility with recent sphinx-tabs.

**Comment by akien-mga** [comment] 2022-03-09 13:19
Fixed by #5670.

![image](https://user-images.githubusercontent.com/4701338/157449445-95ab97e5-dff0-480d-9f5c-9780c744e297.png)

We're now back to the vanilla Sphinx search feature like in the `master` branch. We'll see if we can make `readthedocs-sphinx-search` work properly and provide added value or if we'll stick to vanilla.

**Closed by akien-mga** 2022-03-09 13:19 UTC
Labels: bug, topic:website
