### ISSUE TITLE
Less strict search for html-docs

### ISSUE THREAD

**Issue by ragnarookie** [godotengine/godot-docs#4914] opened 2021-05-14 19:14 UTC
More of a QOL-Enhancement.

Your Godot version:  Not relevant, as it's about the docs and not the engine, but the issue can be seen in different versions of the docs, see the links below.

How it currently works:
The search-engine of the html-docs wont find anything until it's an exact match. 
For example it does not find "set_process_unhandled_input" if I just search for "set_process_unhandled". So unless I know exactly what I want, I usually will not find anything, which kinda beats the reason for the search function. 

How it should work:
Contrary to the Html-Version, if I use the inbuilt Help-Function in the Godot-Engine, the search-function will give me instant results and once I reach typing "set_process_u" it's narrowed down to two options.

Urls:
https://docs.godotengine.org/en/stable/index.html
https://docs.godotengine.org/en/3.2/index.html

**Comment by pycbouh** [comment] 2021-05-14 19:20
We have little control over how ReadTheDocs' search works, but there are alternative possibilities in works. See https://github.com/godotengine/godot-docs/issues/4461.

**Comment by Calinou** [comment] 2021-05-14 19:30
Duplicate of https://github.com/godotengine/godot-docs/issues/4461 (same cause).

**Closed by Calinou** 2021-05-14 19:30 UTC
Labels: enhancement
