### ISSUE TITLE
Add known issues to 2.1 docs

### ISSUE THREAD

**Issue by bojidar-bg** [godotengine/godot-docs#362] opened 2017-04-01 15:27 UTC
(migrated from [godotengine/godot#7580](https://github.com/godotengine/godot/issues/7580) by @RandomShaper)

There are some bugs/inconsistencies in how angle functions works (`atan2`, `angle_to_point`, etc.) that won't be fixed until 3.0 for compatibility.

The thing is that I find sometimes digging among issues to recall which ones were affected.

What I am proposing is adding a _Known Issues_ section to the 2.1 docs with a summary about this so it gets documented and easily checkable.

**Comment by akien-mga** [comment] 2017-06-08 11:38
A first step would be to list such known issues here.

**Comment by pwab** [comment] 2017-07-18 19:23
> A first step would be to list such known issues here.

Well I started working on this. Thanks to the GitHub API and some python scripts this could also be kind of automated. But for this I need more info or let's say: tagging.

**Some statistics: Issues by label**
- `bug`: 952
- `confirmed`: 138
- `bug` + `confirmed`: 127
	- Difference comes from confirmed enhancements... which seem to be bugs sometimes!?)
- `bug` + `pr welcome`: 12
- `bug` + `pr welcome` + `confirmed`: 5
	- This is interesting - why there is a difference?

I'm a bit confused by the use of `confirmed` and `pr welcome`.
Btw. what is the difference between `enhancement` and `feature proposal`? 😅 

There are also some issues, which are marked as `bugs` but **not** `confirmed` and `have comments` but are **not** labeled as `discussion`. (When filtered for more than 10 comments there are 48 issues. There are 143 issues with more than 5 comments.)
Would be good to know, if these bugs-labeled issues are being discussed because they can't be reproduced or because the contributors are searching for a solution (then these issues need a `confirmed` label).'

Would be great if someone could clear things up here. In the meantime I'm going to work on a list with issues labeled as confirmed bugs.

*'used filter:* `is:issue is:open label:bug -label:confirmed comments:>5 -label:discussion`

**Comment by vnen** [comment] 2017-07-19 01:43
> Btw. what is the difference between enhancement and feature proposal?

`enhancement` wants to change an existing feature or workflow, `feature proposal` wants to add something Godot does not yet have.

`discussion` should be used if there's no consensus about the issue or the way to implement it. Sometimes there are long threads just trying to find the cause of the bug, but it's not a "discussion" per se.

`confirmed` is mostly a way to say that the bug can be reproduced consistently, so the triagers don't need to try to reproduce it anymore. `pr welcome` is a way of saying "yeah, this is cool but the regular devs won't work on it anytime soon, feel free to contribute".

And, of course, all issues are labeled by humans which are prone to misunderstandings and they have different POV about it.

---

In any case, I think the original point is not just about *all* reported bugs (people can just check GitHub for that), but about the problems we know we have with Godot 2.1 that won't be fixed because it requires breaking compatibility. Thinking of it, I would add "common pitfalls" to this list.

**Comment by Calinou** [comment] 2020-04-08 14:43
Related to #537.

I'll close this issue as Godot 3.0 was released a long time ago. See https://github.com/dploeger/godot-migrationnotes :slightly_smiling_face:

**Closed by Calinou** 2020-04-08 14:43 UTC
