### ISSUE TITLE
Clarify how exporting to consoles work

### ISSUE THREAD

**Issue by noidexe** [godotengine/godot-docs#3516] opened 2020-05-10 02:42 UTC
**Your Godot version:** 3.x+

**Issue description:**
The docs on exporting to consoles try their best to explain why their is no official support for consoles and to explain that it IS available through third party companies, but bases on what I've read on several forums(HN, reddit, etc) I think many are comparing how exporting to console works with Godot to an incorrect assumption on how it works with other engines and dismissing Godot as an option based on that. 

Many devs have never published to consoles but don't want to get stuck with an engine that doesn't offer support for them. When they read "Godot currently does not officially support consoles" they may assume that it is not possible to build Godot games for switch and that the companies listed below will charge for doing a port from scratch, something that will take a lot of time and be very expensive. 
They may also assume that, when using Unity or Unreal, porting to `CONSOLE` is as simple as pressing a button, not knowing about the process of being approved by `VENDOR`, signing an NDA, aquiring a devkit, getting access to the export tools through some private channel, adapting the code to implement the console features, and the whole process of certification. 

All this false assumptions might give the impression that bringing Godot games to consoles is much harder and expensive than using another engine. 

I think it should be clarified that the process is exactly the same with Godot than with, say, Unreal. The only difference being that in the case of Unreal it is the same company (Epic Games) the one providing both the base engine and the export tools for `CONSOLE` while in the case of Godot you can get the base engine from godotengine.org and the export templates for `CONSOLE` from one of the third party providers listed in the docs. 
See here for reference: https://www.unrealengine.com/en-US/blog/launch-your-game-on-the-nintendo-switch-with-unreal-engine-4-16

Another thing that might be confusing users is that there is no mention of console support int he main page where features are listed. See https://godotengine.org/features
![image](https://user-images.githubusercontent.com/526829/81489613-0a87d580-924e-11ea-9d6f-3c9712ed6da1.png)
Unless there is some legal impediment, I think you should add something like the following there:
- **Console support:** Several consoles supported through third party providers [[know more]](https://docs.godotengine.org/en/stable/tutorials/platform/consoles.html)

I believe the aforementioned clarifications will allow users to make a better informed comparison when deciding whether to choose Godot or not for their projects. 

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/tutorials/platform/consoles.html

**Comment by Calinou** [comment] 2020-05-10 13:04
Duplicate of #2330.

**Closed by Calinou** 2020-05-10 13:04 UTC
Labels: enhancement
