### ISSUE TITLE
Shader matrix column/row major ordering very unclear

### ISSUE THREAD

**Issue by CodeSmith32** [godotengine/godot-docs#9616] opened 2024-07-17 03:00 UTC
**Your Godot version:**

Godot v4.2.2

**Issue description:**

The Godot shader language documentation for matrix column- vs. row-major ordering is very unclear:

1. There is no specification as to whether `matx( vecx, vecx... )` [constructor form](https://github.com/godotengine/godot-docs/blob/4.2/tutorials/shaders/shader_reference/shading_language.rst?plain=1#L145) is column- or row- major.
2. The documentation states that [matrix index access is row-major](https://github.com/godotengine/godot-docs/blob/4.2/tutorials/shaders/shader_reference/shading_language.rst?plain=1#L120) (i.e. `matrix[2]` is a row not a column) which completely diverts from GLSL, and also seems like a terrible decision since two-dimensional array access is column-major (`matrix[2][1]` is the 2nd column, then the 1st row). Is this true? Or is it a documentation discrepancy?

**URL to the documentation page:**

Live documentation:
https://docs.godotengine.org/en/stable/tutorials/shaders/shader_reference/shading_language.html#members

GitHub file:
https://github.com/godotengine/godot-docs/blob/4.2/tutorials/shaders/shader_reference/shading_language.rst?plain=1#L112

**Comment by CodeSmith32** [comment] 2024-07-17 03:02
FWIW, with some experimentation (but not with certainty), constructor ordering seems to be column-major.
i.e., `mat3(vec3, vec3, vec3)` *seems* to be vectors of columns, not rows.

**Comment by AThousandShips** [comment] 2024-07-17 15:01
It describes that they are column major, but it's contradictory in the second clause:
> For matrices, use the ``m[column][row]`` indexing syntax to access each scalar

And
> or ``m[idx]`` to access a vector by row index.

So generally it's stated to be column major, which is to match GDScript I assume

But some more clarification would be good

**Comment by Flarkk** [comment] 2024-09-06 18:10
Duplicate of #5850

**Closed** 2024-10-20 02:13 UTC
Labels: enhancement, area:manual, topic:shaders
