### ISSUE TITLE
godot 4 icon changing issue

### ISSUE THREAD

**Issue by bongblender** [godotengine/godot-docs#7609] opened 2023-07-05 08:15 UTC
**Your Godot version:**
godot 4.0.3
**Issue description:**
I followed every steps shown by godot documentation to change the Icon, but still its not working.
**URL to the documentation page:**

**Comment by Calinou** [comment] 2023-07-05 10:19
Try using https://github.com/pkowal1982/godoticon instead, which should work with official Godot 4.x binaries since they use an uncompressed ICO.

PS: Please don't ask support questions here, as this issue tracker is meant to be used for bug reports only. Use one of the other [community channels](https://godotengine.org/community) instead.

**Comment by skyace65** [comment] 2024-01-28 21:54
Closing per Calinou's comment, if you need support please try a community channel first. If you still can't get it to work please provide us a minimal reproduction project so we can see exactly what you're doing.

**Closed by skyace65** 2024-01-28 21:54 UTC
Labels: bug
