### ISSUE TITLE
Suggest documenting a gotcha: Godot FPS tutorial framerate is really slow

### ISSUE THREAD

**Issue by mlabbe** [godotengine/godot-docs#1412] opened 2018-04-29 17:19 UTC
If you compile Godot with `platform=x11` and omit `target`, Godot's FPS tutorial becomes inexplicably slow when you load the space level in part 3.  This had me wondering what was wrong for awhile, especially because my script profiler was showing zero time.

Eventually someone on Discord helpfully mentioned that I was not compiling an optimized Godot target. Launching this scene on my 2.8GHz laptop had me starting to get 1fps.

I recommend adding a warning to the documentation to ensure that an optimized build is being used when launching this level because a modern highend laptop gets 1fps otherwise!

cc @TwistedTwigleg

**Comment by TwistedTwigleg** [comment] 2018-04-29 17:41
Sounds good!

I had a similar issue with the old tutorial, back when I placed all the objects by hand instead of using a gridmap. using a gridmap seemed to fix the issue for my computer, but I was always a target build.

Funnily enough I tried to debug the issue on the old tutorial several times with the profiler and nothing popped up or seemed to be causing the issue. I didn’t think about the difference in builds being an issue.

I’ll add a note in part 3 when I close #1411 (assuming no one closes it before then)

**Comment by reduz** [comment] 2018-04-30 15:33
this sounds like a bug or problem with the demo/tutorial, though. feel free to investigate.

**Comment by mhilbrunner** [comment] 2018-04-30 15:35
As confirmed by reduz, performance shouldn't degrade this much when compiling without `target`.
So this is either something weird in the tutorial or a Godot engine bug.

I'll try to find out, but everyone else who wants to try... feel welcome :)

**Comment by Cevantime** [comment] 2019-04-27 11:21
Old subject but what seems to be causing the problem is enabling SSAO. I tried to add a GIProbe to the testing area scene but it doesn't seems to fix the problem (tested with 3.1)

**Comment by Calinou** [comment] 2020-04-30 08:19
> If you compile Godot with platform=x11 and omit target, Godot's FPS tutorial becomes inexplicably slow when you load the space level in part 3.

I think it would be better to default to `target=release_debug` to avoid this problem altogether, but this would break automated build scripts. This can still be done for 4.0.

**Comment by Calinou** [comment] 2020-06-15 09:23
This should be addressed by https://github.com/godotengine/godot/pull/38972 which prints a message when compiling a debug build. https://github.com/godotengine/godot/pull/33148 will also make it more obvious that you're running a project from a debug build.

**Closed** 2020-09-28 13:56 UTC
Labels: enhancement
