### ISSUE TITLE
Consider using an image format other than PNG

### ISSUE THREAD

**Issue by Jayman2000** [godotengine/godot-docs#6173] opened 2022-09-13 18:52 UTC
**Your Godot version:** N/A

**Issue description:**
At the moment, the doc writing guidelines say

> Before you add or replace any images in the documentation, they should be run through a PNG compressor to save size. You can use the lossless OxiPNG compressor included in [Squoosh](https://squoosh.app/) for this purpose. For heavier images, consider using a lossy compressor like [pngquant](https://pngquant.org/). With it, almost no image quality is lost during compression.

In my experience, lossless WebPs tend to be smaller than PNGs. [I wrote a Bash script that converts all of the images in this repo to lossless WebPs.](https://gist.github.com/Jayman2000/6dab562039cfc3bd44f37e2a46244ebe) On my system, all of the PNG files take up 49MiB of space. Once you convert them to lossless WebPs, they take up 36MiB of space. We could probably save even more space by making some of the images lossy WebPs or AVIF files.

I’m not sure if PDF or EPUB files support these newer image formats, so it might make sense to keep the source files as PNGs and then convert them to another format when building the HTML documentation.

**URL to the documentation page (if already existing):**
<https://docs.godotengine.org/en/latest/community/contributing/docs_writing_guidelines.html#image-contribution-guidelines>

**Comment by Calinou** [comment] 2022-09-13 20:12
I've been thinking about this recently, and I agree with moving towards WebP (both for lossless and lossy images when lossless is too large).

**Comment by TheYellowArchitect** [comment] 2022-09-29 14:33
I can confirm this. For at least a year or so, whenever some1 told me that .webp is more efficient than .jpg, I would disagree because in all my use-cases it wasn't the case, as .jpg in low compression achieves size near .webp

For this https://github.com/godotengine/godot-docs/pull/6243 however, exporting lossless images (.png printed from my screen) to quality 80 of .webp (and no alpha channel), the difference in size is obvious, its like 40%

**Comment by skyace65** [comment] 2022-10-04 02:05
As someone who has updated more images for this documentation than I can count I'm in full agreement with moving to webp. Lossy compression would be one less thing I and everyone else would need to do when updating images. And we could always then move to avif at a later date.

**Comment by mhilbrunner** [comment] 2022-10-04 11:16
If I interpret https://caniuse.com/webp correctly, all current major browser support WebP.
I've been using WebP heavily with Chrome and Firefox at least for other stuff for multiple years now and encountered no issues and have observed similar wins for perf/size reduction.

We may indeed just want to move to WebP (at least for now).

**Closed** 2023-01-22 16:01 UTC
Labels: enhancement
