### ISSUE TITLE
Explicit info about execution order

### ISSUE THREAD

**Issue by pajcek11** [godotengine/godot-docs#3710] opened 2020-06-19 18:23 UTC
**Your Godot version:**
3.2.1

**Issue description:**
The only reference I could find to the question of execution order is a two-sentence chapter called "tree order". This is essential information, so it would be very nice if there would be some documentation outlining the exact execution order of nodes, scripts, signals, inspector values, and their inter-family relations. Signals especially since the order of emitting is a thing of mystery if one does not manually emit the signal. 

From what I gather, code is executed and also rendered top-to-bottom first children then parents, but if this is true, I think it still warrants some deeper explanation.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/latest/getting_started/step_by_step/scene_tree.html#tree-order

**Comment by Calinou** [comment] 2020-06-19 19:10
Duplicate of #3679.

**Closed by Calinou** 2020-06-19 19:10 UTC
Labels: enhancement
