### ISSUE TITLE
Physics interpolation docs

### ISSUE THREAD

**Issue by kkolyan** [godotengine/godot-docs#7973] opened 2023-09-20 22:00 UTC
https://docs.godotengine.org/fi/latest/tutorials/physics/interpolation/using_physics_interpolation.html
seems like this feature is not implemented in stable (both 3 and 4). also, this page absent in EN language: https://docs.godotengine.org/en/latest/tutorials/physics/interpolation/using_physics_interpolation.html

Seems like some mistake

**Comment by AThousandShips** [comment] 2023-09-21 09:20
Duplicate of https://github.com/godotengine/godot-docs/issues/7233

**Closed by AThousandShips** 2023-09-21 09:20 UTC
Labels: bug
