### ISSUE TITLE
Creeps 3D still uses obsolete `Input.is_action_pressed()`

### ISSUE THREAD

**Issue by hmturnbull** [godotengine/godot-docs#6735] opened 2023-02-05 02:32 UTC
**Your Godot version:**
v4.0.beta17.official [c40020513]

**Issue description:**
While working my way through the "Your First 3D Game" section, I noticed that it hasn't been updated with the newer input method.  The current documentation reads as follows:
```
func _physics_process(delta):
    # We create a local variable to store the input direction.
    var direction = Vector3.ZERO

    # We check for each move input and update the direction accordingly.
    if Input.is_action_pressed("move_right"):
        direction.x += 1
    if Input.is_action_pressed("move_left"):
        direction.x -= 1
    if Input.is_action_pressed("move_back"):
        # Notice how we are working with the vector's x and z axes.
        # In 3D, the XZ plane is the ground plane.
        direction.z += 1
    if Input.is_action_pressed("move_forward"):
        direction.z -= 1
```

Given that the 3D tutorial has already taught you how to add controller buttons to the **Input Map**, in addition to the usual physical keys, I think it's doubly important to teach new users to use `Input.get_axis()`, since it's considerably more intuitive than the older method.

I was thinking something like this:
```
func _physics_process(delta):
	# We create a local variable to store the input direction.
	var velocity : Vector3 = Vector3(Input.get_axis("move_left", "move_right"), 0, Input.get_axis("move_foreward", "move_back"))
```

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/latest/getting_started/first_3d_game/03.player_movement_code.html

**Comment by cbscribe** [comment] 2023-02-05 05:34
Duplicate of #6687

**Closed by cbscribe** 2023-02-05 05:34 UTC
Labels: enhancement
