### ISSUE TITLE
Android Plugins and JDK Version

### ISSUE THREAD

**Issue by compese** [godotengine/godot-docs#7395] opened 2023-05-21 03:59 UTC
**Your Godot version:** 4.0.3.stable

**Issue description:**
After following the [android plugin docs](https://docs.godotengine.org/en/stable/tutorials/platform/android/android_plugin.html), `./gradlew build` produces this error (saying jdk 17 should be used):
    
    FAILURE: Build failed with an exception.
    
    * Where:
    Build file '/home/jeremy/AndroidStudioProjects/MyApplication/app/build.gradle' line: 2
    
    * What went wrong:
    An exception occurred applying plugin request [id: 'com.android.application']
    > Failed to apply plugin 'com.android.internal.application'.
       > Android Gradle plugin requires Java 17 to run. You are currently using Java 11.
          Your current JDK is located in /usr/lib/jvm/java-11-openjdk

But the [exporting for android docs](https://docs.godotengine.org/en/stable/tutorials/export/exporting_for_android.html#install-openjdk-11) indicate jdk 11 should be used.

Should the [android plugin docs](https://docs.godotengine.org/en/stable/tutorials/platform/android/android_plugin.html) say that Android Studio should be configured to use jdk 11? Or do the  [exporting for android docs](https://docs.godotengine.org/en/stable/tutorials/export/exporting_for_android.html#install-openjdk-11)  need to be updated?

BTW I changed "File > Settings > Build, Execution, Deployment > Build Tools > Gradle" in Android Studio (Flamingo 2022.2.1 Patch 1 -- which is the current version) to use jdk 11 but I still get the same error.

YMMV but I've tried  following the  [android plugin docs](https://docs.godotengine.org/en/stable/tutorials/platform/android/android_plugin.html) strong recommendation to use Android Studio to generate Android Plugins a few times but that approach has never worked for me. I find it much easier to clone https://github.com/godotengine/godot-google-play-billing.git and modify it (also using the iap_android example in https://github.com/godotengine/godot-demo-projects.git with it as an example). Maybe the Android Plugin docs should recommend this approach instead?

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/tutorials/platform/android/android_plugin.html
https://docs.godotengine.org/en/stable/tutorials/export/exporting_for_android.html#install-openjdk-11

**Comment by compese** [comment] 2023-05-24 20:24
It looks like the Android Gradle Plugin (AGP) 8.0.0 upgrade is the problem, JDK 17 is a hard requirement. From what I can tell so far, downgrading AGP in Android Studio isn't a good option. So I'm looking at pre-AGP 8 versions of Android Studio
https://developer.android.com/build/releases/gradle-plugin#jdk-17-agp
https://developer.android.com/build/releases/gradle-plugin#8-0-0

**Comment by compese** [comment] 2023-05-24 20:25
How difficult would it be to update Godot to allow JDK 17?

**Comment by compese** [comment] 2023-05-24 21:45
Creating the Android plugin with [Android Studio Electric Eel | 2022.1.1 Patch 2](https://developer.android.com/studio/archive) works . So one fix could be to direct people to this version of Android Studio. But it would be better for Godot to support JDK 17.

**Comment by compese** [comment] 2023-05-25 00:46
submitted PR https://github.com/godotengine/godot-docs/pull/7416

**Comment by m4gr3d** [comment] 2023-05-29 16:09
> It looks like the Android Gradle Plugin (AGP) 8.0.0 upgrade is the problem, JDK 17 is a hard requirement. From what I can tell so far, downgrading AGP in Android Studio isn't a good option. So I'm looking at pre-AGP 8 versions of Android Studio https://developer.android.com/build/releases/gradle-plugin#jdk-17-agp https://developer.android.com/build/releases/gradle-plugin#8-0-0

Downgrading AGP is fine; it's actually recommended to avoid newer versions of AGP as they have often bugs, which is one of the reasons Godot itself is using AGP 7.2.1.

**Comment by m4gr3d** [comment] 2023-05-29 16:11
> YMMV but I've tried following the [android plugin docs](https://docs.godotengine.org/en/stable/tutorials/platform/android/android_plugin.html) strong recommendation to use Android Studio to generate Android Plugins a few times but that approach has never worked for me. I find it much easier to clone

What issue do you run into when trying to generate using Android Studio?
The `Google Play Billing` project is not designed as a template / starter project, so it's better to improve the documentation to address any shortcomings then to direct users to use it as a starter project.

**Comment by compese** [comment] 2023-05-29 19:23
responded in https://github.com/godotengine/godot-docs/pull/7416

**Comment by tinxx** [comment] 2023-11-01 06:26
I have also stumbled across the problem that *Exporting for Android* states to use OpenJDK11.
I can confirm that at least with the upcoming Godot 4.2 it works only using OpenJDK 17. I have built the Android export templates and Android plugins (v2) using 17.

**Comment by m4gr3d** [comment] 2023-11-01 06:31
> I have also stumbled across the problem that *Exporting for Android* states to use OpenJDK11.
> I can confirm that at least with the upcoming Godot 4.2 it works only using OpenJDK 17. I have successfully built the Android export templates and Android plugins (v2) using 17.

@tinxx The documentation has been updated to state to use JFK 17.
See https://docs.godotengine.org/en/latest/tutorials/export/exporting_for_android.html

**Comment by m4gr3d** [comment] 2023-11-01 06:32
Closing this issue as it has been resolved in Godot 4.2

**Closed** 2023-11-01 06:32 UTC
Labels: bug, area:manual

**Comment by tinxx** [comment] 2023-11-01 06:33
> > I have also stumbled across the problem that _Exporting for Android_ states to use OpenJDK11.
> > I can confirm that at least with the upcoming Godot 4.2 it works only using OpenJDK 17. I have successfully built the Android export templates and Android plugins (v2) using 17.
> 
> @tinxx The documentation has been updated to state to use JFK 17. See https://docs.godotengine.org/en/latest/tutorials/export/exporting_for_android.html

My bad, I was refering to *Compiling for Android[¶](https://docs.godotengine.org/en/latest/contributing/development/compiling/compiling_for_android.html#compiling-for-android)*

**Comment by m4gr3d** [comment] 2023-11-01 06:35
> > > I have also stumbled across the problem that _Exporting for Android_ states to use OpenJDK11.
> > > I can confirm that at least with the upcoming Godot 4.2 it works only using OpenJDK 17. I have successfully built the Android export templates and Android plugins (v2) using 17.
> > 
> > @tinxx The documentation has been updated to state to use JFK 17. See https://docs.godotengine.org/en/latest/tutorials/export/exporting_for_android.html
> 
> My bad, I was refering to *Compiling for Android[¶](https://docs.godotengine.org/en/latest/contributing/development/compiling/compiling_for_android.html#compiling-for-android)*. It should be bumped to 17, too.
> 

It's being updated in https://github.com/godotengine/godot-docs/pull/8368
