### ISSUE TITLE
Left drawer overlaps documentation content on 5:4 monitor

### ISSUE THREAD

**Issue by MegadronA03** [godotengine/godot-docs#6196] opened 2022-09-18 21:05 UTC
**Issue description:**
![image](https://user-images.githubusercontent.com/56801003/190927812-42cf012f-9681-4dfa-80ce-bce70f597032.png)
Left drawer overlaps documentation content on 5:4 monitor. 

![image](https://user-images.githubusercontent.com/56801003/190927938-77a54196-598a-43d1-813a-3baa734ffc5b.png)
Zooming out(50%) and updating the page does not resolve the issue.

![image](https://user-images.githubusercontent.com/56801003/190928065-68b76960-bfd3-4a6f-a91e-cc5aba43797c.png)
But zooming in and out fixes the problem.

Fix layout or make an option to minimize left drawer.

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/development/cpp/core_types.html#:~:text=Godot%20uses%20the%20standard%20C99,nowadays%20supported%20by%20every%20compiler.

**Comment by YuriSizov** [comment] 2022-09-19 13:33
That's unrelated to your screen dimensions. This is because of the extra context added by the search engine that your browser is trying to focus on, breaking the page's layout.

It's a duplicate of https://github.com/godotengine/godot-docs/issues/4790.

**Closed by YuriSizov** 2022-09-19 13:33 UTC
Labels: bug, topic:website
