### ISSUE TITLE
Godot docs switch to Russian randomly

### ISSUE THREAD

**Issue by tavurth** [godotengine/godot-docs#3370] opened 2020-04-11 10:24 UTC
Godot docs keep randomly switching to Russian for me. I have no Russian language settings in my browser, and I'm not searching anything in Russian.

**Sometimes the sidebar**
<img width="1440" alt="Screenshot 2020-04-11 at 16 05 57" src="https://user-images.githubusercontent.com/100964/79041312-89b5c980-7c0e-11ea-958b-d38e8a939b28.png">

**And sometimes the headers**
<img width="724" alt="Screenshot 2020-04-11 at 16 08 32" src="https://user-images.githubusercontent.com/100964/79041337-bbc72b80-7c0e-11ea-951a-e425c22bfffb.png">

(Couldn't grab this one in Russian)

**Comment by pycbouh** [comment] 2020-04-11 10:47
It's Ukrainian. The issue is you are browsing the "uk" version of docs, not the "en" version. But the Ukrainian version is not complete and parts are shown in English.

Related to #3367, #1520 and #1574.

**Comment by Calinou** [comment] 2020-04-11 11:31
Duplicate of #1574.

**Closed by Calinou** 2020-04-11 11:31 UTC

**Comment by pycbouh** [comment] 2020-04-11 11:34
Well, there is this menu at the bottom as well...

![image](https://user-images.githubusercontent.com/11782833/79042550-69cbd900-7c01-11ea-94f5-507b7b87ca13.png)

**Comment by tavurth** [comment] 2020-04-11 13:50
Hmm, guess it was caused by accessing mostly from google search rather than directly.

Perhaps it could detect my language settings from browser and suggest to switch?

**Comment by Calinou** [comment] 2020-04-11 13:55
> Perhaps it could detect my language settings from browser and suggest to switch?

That can be done with some JavaScript. I would prefer if we found a way to remove non-English pages from search results still.
