### ISSUE TITLE
C# - To brace, or not to brace

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot-docs#2504] opened 2019-06-04 22:39 UTC
In C#, you normally write if statements like this:

```
if (condition)
{
    DoSomething();
}
```

But for single statements, you also have this option:

```
if (condition)
    DoSomething();
```

I personally prefer to always use the former, since to me it's more readable, but we should probably pick one and put it in [the style guide](https://docs.godotengine.org/en/latest/getting_started/scripting/c_sharp/c_sharp_style_guide.html). @neikeq & anyone else.

There's also the matter of one block using braces and one not. I've seen this before:

```
if (condition)
{
    DoSomething();
    DoMoreThings();
}
else
    DoSomethingElse();
```

**Comment by Calinou** [comment] 2019-06-04 22:51
I would vouch for the former as well: always use braces, as it makes refactoring easier and decreases the risk of mistakes. (I've already fallen victim to this issue several times in C++…)

**Comment by neikeq** [comment] 2019-06-05 01:14
I skip braces for single statements. You save quite some vertical space. In the case where one branch uses braces (like in your last example), then the other branches should as well.

**Comment by NathanLovato** [comment] 2020-09-27 15:12
What's the state of this discussion? Is for a C# style-guide for the Godot docs?

**Comment by Calinou** [comment] 2020-09-27 15:16
@NathanLovato The current [C# style guide](https://docs.godotengine.org/en/latest/getting_started/scripting/c_sharp/c_sharp_style_guide.html) does not make a recommendation for single-line braces. It only advises you to put the brace on a new line.

**Comment by NathanLovato** [comment] 2020-09-27 15:25
Okay seems it's a matter of making a decision. Always having braces sounds good to me for visual consistency. I recall a presentation about how that related to typography and had been studied to help people read code, along with other guidelines (short lines, etc.), but can't remember the name. It was about C++ I think.

Regardless, I think straightforward rules are good for users: always having brackets the same way is the simplest way to go about formatting, it always separates code well, helping anyone read it. I'd bet you can also let your formatter place them for you too.

Would you all be fine with that?

**Comment by neikeq** [comment] 2020-09-27 15:42
The problem is C# places the opening braces on a new line, so always using braces for a single statement wastes a lot of vertical space.

**Comment by NathanLovato** [comment] 2020-09-27 15:59
Sure. Now, does the consistent use of brackets make it harder or easier for newcomers to understand code examples in the docs? I'd argue:

1. Vertical space isn't a resource we have in limited supply so we can use as much as we want.
2. As long as examples fit vertically in a web page, the few added lines don't require you to scroll, so they're not adding inconvenience.

Note we're talking about a _guideline_ for the docs and maybe official demos here, not a hard rule. With GDScript we have a guideline to have 2 lines between functions, but for short examples in the docs, it looked off, so in those cases, we agreed to only use 1. The guideline is still as simple as possible for users: we recommend 2 lines between functions without exceptions.

Either way, we need to make a decision and close this.

**Comment by aaronfranke** [comment] 2020-09-27 16:19
I would prefer to always enforce them because it would be consistent, an easy rule to follow, and usually improves readability. However, to see a strong case in favor of allowing no braces, you can take a look at [this code](https://github.com/godotengine/godot/blob/master/modules/mono/glue/GodotSharp/GodotSharp/Core/AABB.cs#L357-L368).

**Comment by NathanLovato** [comment] 2020-09-27 16:25
Considering we're talking about a guideline, to me, it's fine to have exceptions, like when you have 5+ if blocks with only one instruction in a row.

**Comment by neikeq** [comment] 2020-09-28 08:02
If it's only docs guidelines that would be ok.

**Comment by tetrapod00** [comment] 2024-12-14 08:39
Seems like we decided, in general, to brace. See discussion in https://github.com/godotengine/godot-docs/pull/6641#discussion_r1083270198.

We should write this down in the C# style guide.

**Closed** 2024-12-14 09:16 UTC
Labels: discussion, topic:dotnet
