### ISSUE TITLE
Better documentation for Visual script . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-docs#3671] opened 2020-06-10 07:22 UTC
**Your Godot version:**
Godot 3.2

**Issue description:**
I've been looking at the official pages, for common visual script nodes, and it has nice text, but it would be nice, if there were pictures, as well, that explains how the boxes ( sequence, switch, condition, return ) work, like how one must use inspector, to actually ' make ' them work . .

In other doc pages, there are animated pictures, that show how to do things, I have found free, open source, anime gif program, ScreenToGif, to make them, free . . It would be nice if there were some examples, and a dedicated ' Make your first game in Visual script ' tutorial, same as one, for GDScript, maybe a 2D tutorial, also a 3D tutorial . . .

**URL to the documentation page (if already existing):**

https://docs.godotengine.org/en/stable/classes/class_visualscriptcondition.html

**Comment by jasperbrooks79** [comment] 2020-06-10 07:25
If you want, I would like to work on making a good written tutorial, in official docs, for making first 3D game, using only visual script . . IF the docs were made better, the official ones, I wouldn't have to ask so many questions, online <3 Sry . .

Anyway, I have some really good ideas, make a tutorial that makes a game, and that explains all the major node boxes, but with an example, when you're done, you have a simple game, as well . . And, you know 90 % of the boxes, from there . . . And, also can do some cool stuff, like change a texture, on an enemy, as it gets damaged, or make a simple cut-scene, or so . . .

**Comment by jasperbrooks79** [comment] 2020-06-10 07:27
My point is, thank you, it would be nice if there was a make your first 2D game, in visual script, and make your first 3D game, in visual script, from start, to finish, that can be exported, and run on Windows, Linux, maybe Mac ( not sure, how to ) . . And, that the makers of the engine read it afterwards, and say if there were big mistakes, but WHEN the entire tutorial is done, if needed, for better games . . .

**Comment by Calinou** [comment] 2020-06-10 08:22
Duplicate of #466 and #533.

**Closed by Calinou** 2020-06-10 08:22 UTC
Labels: enhancement
