### ISSUE TITLE
Proposal: better class discoverability, organisation and a hierarchy through the use of tags/groups/categories.

### ISSUE THREAD

**Issue by Splizard** [godotengine/godot-docs#6137] opened 2022-09-05 05:51 UTC
_Consider this user story:_
A developer is building a game in Godot and is adding physics to their game. They wish to explore all of the physics related classes that Godot has to offer. 

There are currently three ways to discover classes on https://docs.godotengine.org/

1. **The Class Reference**
    Contains _a huge_ and complete list of every class from A-Z. It's not so clear to see which classes are physics related, it's easy to miss one when going through the list and there are a ton of classes there.
2. **Search**
    Classes can be returned by searches if their pages have matching text from the search query. The search term "physics" returns a number of results but is fairly verbose and does not necessarily return all physics-related classes.
3. **Referenced by a tutorial**
    The core tutorials will reference any required classes. There is a section on Physics, but this section does not list any classes, instead each tutorial needs to be visited and again it is not clear that a complete set of physics-related classes will be listed within.

I don't believe any of these paths are useful for the user story in question.

**Proposal**
Instead, I believe it would be valuable to organise the classes available in Godot into a total hierarchy where each class is associated with a single 'core' tag/group/category. These would be available as a subsection on the https://docs.godotengine.org/ sidebar and each one would contain a list of the related classes. An additional set of tags could be associated with a class, such as whether it relates to 2D or 3D.

For example:
`physics` would be a core tag/group/category and the classes listed on the page would include:

* CollisionShape2D
* PhysicsServer2D
* PhysicsServer3D
* RayCast2D
* RayCast3D
* etc.

The tag/group/category types should reflect https://godotengine.org/teams

**Work Required**
Somebody would need to go through each class and assign them to the appropriate categories/tags/groups. New classes would need to be assigned to the appropriate categories/tags/groups.

(If this proposal is accepted, I would be keen to make an attempt to do this.)

**Inspired By**
https://twitter.com/splizard/status/1566647326969499649

**Comment by YuriSizov** [comment] 2022-09-05 11:43
This is a duplicate of https://github.com/godotengine/godot-proposals/issues/4543.

**Closed by YuriSizov** 2022-09-05 11:43 UTC
Labels: enhancement
