### ISSUE TITLE
Gamecenter example

### ISSUE THREAD

**Issue by stonekase** [godotengine/godot-docs#3127] opened 2020-01-30 12:44 UTC
There is absolutely no clear example of gamecenter implementation on the IOS.
Please anyone can redirect me with a gd script example.
how do i access the return values of (Gamecenter.request_identity_verification_signature)

**Comment by Calinou** [comment] 2020-01-30 16:22
Duplicate of #2715.

**Closed by Calinou** 2020-01-30 16:22 UTC
