### ISSUE TITLE
angle_to_point incorrect

### ISSUE THREAD

**Issue by Scottz0r** [godotengine/godot-docs#2414] opened 2019-04-28 01:13 UTC
Vector2’s angle_to_point seems to be really _from_ the given point.

In the documentation, [2D movement overview](https://docs.godotengine.org/en/3.1/tutorials/2d/2d_movement.html) > Rotation + movement (mouse) , has a player object look in the direction of the cursor. It assigns the rotation of the player by the following script:

```
rotation = get_global_mouse_position().angle_to_point(position)
```

The code _reads_ that the angle_to_point should be returning the angle from the mouse to the player’s position. Mouse to Player wouldn’t make sense because that angle would be flipped 180 degrees. Yet, the code in the example is correct and makes the demo work. The function seems to be using the parameter as a _from_ point and not a _to_ point as the documentation and function name suggests.

When manually computing the rotation without using angle_to_point, I use the following to get the vector from the Player’s position to the Mouse’s position (using the definition of vector addition of `From + X = To`, or `X = To - From`).

```
X = Mouse Position - Player Position
```

A normal vector from this results in the same normal vector as angle_to_point in the demo, which supports my suspicion that angle_to_point is computing in the "wrong" direction. I have attached a demo project that compares various calculations with angle_to_point: [rotation_testing.zip](https://github.com/godotengine/godot-docs/files/3124485/rotation_testing.zip)

If I am not making some obvious mistake, then the documentation should clarify the directionality of this method. Perhaps renaming the parameter to "from" and adding something like:

```
Returns the angle in radians between the line connecting the two points and the x coordinate. The line is computed starting from the given vector.
```

**Comment by Calinou** [comment] 2020-02-26 11:08
Duplicate of #16307.

**Closed by Calinou** 2020-02-26 11:08 UTC
