### ISSUE TITLE
Expanded preferences in sidebar is hard to distinguish from expanded chapters

### ISSUE THREAD

**Issue by mega-bit** [godotengine/godot-docs#3193] opened 2020-02-19 20:01 UTC
When the preferences on the bottom of the sidebar are collapsed they have a light blue border on top which lets it stand out from expanded chapters which are colored in the same dark blue as the preferences panel.

When the preferences are expanded that border is gone (see screenshot) and I found myself having trouble to make out where the preferences panel begins.

![image](https://user-images.githubusercontent.com/43795127/74870549-359f0f00-535a-11ea-8284-5eb9583e5eb2.png)

**Comment by Piralein** [comment] 2024-03-13 13:26
The panel now contains a "box-shadow" in both the light and dark theme. (technically its a transparent before element)
closing as the issue is resolved in newer versions.

![panel](https://github.com/godotengine/godot-docs/assets/48352564/e6a1c8ed-daf3-4624-9ee9-b6e709866d44)

**Closed by Piralein** 2024-03-13 13:26 UTC
Labels: bug, content:website
