### ISSUE TITLE
Shortcuts for switching scripts in the editor don't work

### ISSUE THREAD

**Issue by dark-penguin** [godotengine/godot-docs#1713] opened 2018-08-29 03:38 UTC
The default shortcut for "Next Script" does not work (probably because it's "Control-Shift-Period", and pressing Shift+Period gives you the ">" symbol instead of Period).

What's more important, the shortcut I want to set also does not work. I want to switch scripts with Ctrl+PgUp/Ctrl+PgDn, like it has been in Gnome Terminal and other places from time immemorial. This does not work - probably because the editor intercepts this shortcut and gives it some useless function, which is not configurable (though it looks to me like it's behaving the same as just PgUp/PgDn). Ctrl+Up/Ctrl+Down also don't do anything but can not be mapped to switching scripts.

Also, wouldn't it be possible to add a shortcut for "Last Script" (Ctrl+Tab by default) for switching between the current script and the last used script? The difference from "History Prev" is that pressing Ctrl+Tab for the second time would get you back to the current script, which is convenient for comparing two scripts or working with a reference.

**Comment by Meriipu** [comment] 2020-06-23 10:09
this might be posted in the issue tracker of the wrong repo.

I can not reproduce the first issue in 3.2.2 though (ctrl+shift+period works for me to cycle scripts)

**Comment by Calinou** [comment] 2020-06-23 10:19
@Meriipu This is indeed not an issue within the documentation, closing.

**Closed by Calinou** 2020-06-23 10:19 UTC

**Comment by dark-penguin** [comment] 2020-06-23 10:25
Ooooopps, sorry!!
