### ISSUE TITLE
Godot docs in other lang

### ISSUE THREAD

**Issue by Omaranwa** [godotengine/godot-docs#468] opened 2017-09-13 10:23 UTC
what about that , can it be done?

**Comment by Noshyaar** [comment] 2017-09-13 11:32
Duplicate of #4, https://github.com/godotengine/godot/issues/10499

**Comment by NathanLovato** [comment] 2017-09-13 11:33
If and when we reach a good completion rate in the docs and API reference, we'll look into ways to translate them. Until then, and with Godot 3, everything is still subject to change, and we still lack contributors for the EN one. And yes, duplicate of #4, closing the issue

**Closed by NathanLovato** 2017-09-13 11:33 UTC
