### ISSUE TITLE
Warning documentation Godot 4.1 using Godot 3.x syntax

### ISSUE THREAD

**Issue by Gecko102** [godotengine/godot-docs#8507] opened 2023-11-20 02:37 UTC
**Your Godot version:**
4.1

**Issue description:**
Online documentation page for "GDScript warning system" is using #warning-ignore:warning-id instead of @warning_ignore(warning-id)

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/warning_system.html

If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

**Comment by AThousandShips** [comment] 2023-11-20 09:35
Duplicate of https://github.com/godotengine/godot-docs/issues/8145

**Closed by AThousandShips** 2023-11-20 09:35 UTC
Labels: bug
