### ISSUE TITLE
Your first 2D game - C# code snippets for movement are wrong and cannot compile

### ISSUE THREAD

**Issue by vverdier** [godotengine/godot-docs#6893] opened 2023-03-05 09:06 UTC
**Your Godot version:**
v4.0.stable.mono.official [92bee43ad]

**Issue description:**
The C# code snippets for movement are wrong and cannot compile

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/getting_started/first_2d_game/03.coding_the_player.html

References to Vector2 fields X and Y should be in uppercase instead of lowercase

**Comment by raulsntos** [comment] 2023-03-05 14:07
Duplicate of https://github.com/godotengine/godot-docs/issues/6878

**Closed by raulsntos** 2023-03-05 14:07 UTC
Labels: bug

**Comment by vverdier** [comment] 2023-03-05 15:56
Sorry I searched before if the issue was already opened... I didn't know the "first 3d game" was the same game and had the same issues.

**Comment by raulsntos** [comment] 2023-03-05 16:05
Oh, don't worry. I just closed this because it refers to the same getting started section of the documentation, you are right that the _Your first 2D game_ and the _Your first 3D game_ tutorials are different, but they both contain the same issues because neither has been updated for 4.0 yet.

There's already a PR open that should fix these issues in both tutorials: https://github.com/godotengine/godot-docs/pull/6811.

Also, thank you for opening the issue.
