### ISSUE TITLE
Why does the Encrypting Save Games page hate mobile gamers?

### ISSUE THREAD

**Issue by ShatReal** [godotengine/godot-docs#4022] opened 2020-09-16 15:59 UTC
**Your Godot version:**
3.2.2

**Issue description:**
Why does the Encrypting Save Games page hate mobile gamers?
I quote,

> These individuals need to keep focusing on their video games (because not doing so will fill them with tremendous existential angst), so they go as far as spending money on them to extend their experience, and their preferred way of doing so is through in-app purchases and virtual currency.

> But what if someone were to find a way to edit the saved games and assign the items and currency without effort? That would be terrible, because it would help players consume the content much faster, and therefore run out of it sooner than expected. If that happens, they will have nothing that prevents them from thinking, and the tremendous agony of realizing their own irrelevance would again take over their life.

I don't understand. What is the point of this? Just because some mobile games have terrible practices doesn't mean you should randomly shove your rant about how much you hate the people who play games like that in the front of a documentation page. Not everyone feels "tremendous agony" when they "realize their own irrelevance", only people who care only about becoming famous.

If this kind of stuff is acceptable in documentation, am I allowed to edit the "2D Sprite animation" tutorial to start with a rant about how much I hate people with bad teeth, then?

**URL to the documentation page (if already existing):**
https://github.com/godotengine/godot-docs/blob/master/tutorials/io/encrypting_save_games.rst

**Comment by Calinou** [comment] 2020-09-16 16:09
Duplicate of https://github.com/godotengine/godot-docs/issues/373 and many other issues.

There are no plans to remove this section from the documentation. We regularly see comments from people who find that part of the documentation to be a welcome refresher in the middle of "serious" documentation: #2512 (comment)

**Closed by Calinou** 2020-09-16 16:09 UTC
Labels: enhancement

**Comment by akien-mga** [comment] 2020-09-16 17:22
Hint: it's a sarcastic/humorous piece of documentation. It's not meant to be taken seriously...
