### ISSUE TITLE
Missing '@' symbol in an export tag

### ISSUE THREAD

**Issue by jaymehta-g** [godotengine/godot-docs#7924] opened 2023-09-15 21:30 UTC
**Your Godot version:**
4
**Issue description:**
There is a missing @ symbol in the second code block

```
# This type's value varies, i.e. it is a variable, so it uses snake_case.
@export var script_type: Script

# Must configure from the editor, defaults to null.
export var const_script: Script:
^^^ here!
    set(value):
        if Engine.is_editor_hint():
            const_script = value
```

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/tutorials/best_practices/godot_interfaces.html

**Comment by AThousandShips** [comment] 2023-09-16 08:12
Duplicate of https://github.com/godotengine/godot-docs/issues/7760

**Closed by AThousandShips** 2023-09-16 08:12 UTC
Labels: bug
