### ISSUE TITLE
Suggested normal map direction is wrong

### ISSUE THREAD

**Issue by kubajz22** [godotengine/godot-docs#4555] opened 2021-01-17 14:33 UTC
**Your Godot version:**
3.2.3-stable

**Issue description:**
The documentation says that you should use a normal map whose directions are X+, Y-, Z+. This is most likely incorrect.
**1)** It is in contrary with the OpenGL convention.
**2)** I have baked two normal maps in Blender. One with the Y being positive and another being negative. I then imported them into Godot and put them on a mesh. The Y+ was lit correctly. This corresponds with my observations on many other models I made. They only looked correct when the Y channel was "pointing up" (Y+).

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/tutorials/3d/spatial_material.html
The same note is also here:
https://docs.godotengine.org/en/stable/getting_started/workflow/assets/importing_images.html#normal-map

I know that Zylann already pointed this out, but it has been almost 4 months and the documentation is still the same. This mistake can cause a lot of wasted time and confusion (which it did), yet the fix is as simple as changing 2 characters.

**Comment by skyace65** [comment] 2021-01-17 15:30
If you think that the documentation isn't being fixed fast enough feel free to open a pull request yourself to fix it.

**Comment by pycbouh** [comment] 2021-01-17 17:12
> I know that Zylann already pointed this out

There is no need to create more than one issue for a single problem. Closing as a duplicate of #4192.

**Closed by pycbouh** 2021-01-17 17:12 UTC
Labels: bug
