### ISSUE TITLE
Godot 4.2 errors

### ISSUE THREAD

**Issue by Windowsuser32** [godotengine/godot-docs#8717] opened 2024-01-03 22:44 UTC
**4.2.1**

**I copypasted the code in the documentation to get started but its giving me a lot of errors.**

**https://docs.godotengine.org/en/stable/tutorials/2d/index.html**

If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

**Comment by AThousandShips** [comment] 2024-01-04 10:41
Please provide any info on what the issue is, just "lots of errors" doesn't tell us anything and we can't help at all

For support questions and help please first turn to the other [community channels](https://godotengine.org/community), this is for bug reporting, not a help desk. Please use other channels *first* to see if this is a bug or user error.

**Comment by skyace65** [comment] 2024-01-28 14:13
Closing due to the lack of a response and lack of information. If you open a issue again you need to give us specific information on the page, and the specific part of the page you are having issues with. We can't help you without that.

**Closed by skyace65** 2024-01-28 14:13 UTC
Labels: bug
