### ISSUE TITLE
Rearrange list items in member descriptions of all classes

### ISSUE THREAD

**Issue by MaaaxiKing** [godotengine/godot-docs#5075] opened 2021-07-08 18:13 UTC
**Your Godot version:**
3.3.2.stable.mono
**Issue description:**
Every signal, enumeration, property and method has its own unordered list with one list item each. That's terrible, make one list for every structure and if needed (in enumerations), nested lists!
**URL to the documentation page (if already existing):**
E.g., https://docs.godotengine.org/de/stable/classes/class_node.html#class-node#:~:text=Signals

**Comment by Calinou** [comment] 2021-07-08 19:30
This is likely done by design. The bullet points are help to improve readability and give you a point of reference when scrolling.

**Comment by MaaaxiKing** [comment] 2021-07-08 21:08
Of course, we should have bullet points xD. But when looking in the source data, every item has its own list (`<ul>`), not just a list item (`<li>`), that's not how lists are supposed to be used.

**Comment by Calinou** [comment] 2021-07-08 21:26
> But when looking in the source data, every item has its own list (<ul>), not just a list item (<li>), that's not how lists are supposed to be used.

The HTML is automatically generated from the reStructuredText source. We have no control over it.

Also, as far as I know, `<li>` outside of `<ul>`/`<ol>`/`<dl>` is not valid HTML.

**Comment by tetrapod00** [comment] 2024-11-16 03:03
Closing this issue, since this seems to have been fixed in both 3.6 and 4.3/stable. The class reference no longer uses bullet points at all.

**Closed by tetrapod00** 2024-11-16 03:03 UTC
Labels: enhancement, area:class reference, content:website
