### ISSUE TITLE
Document event, method and signal execution order

### ISSUE THREAD

**Issue by lazyvainglory** [godotengine/godot-docs#3679] opened 2020-06-13 09:13 UTC
**Your Godot version:**
3.2.1
**Issue description:**
There's no documentation about the event, method and signal execution order. 
Something like this https://docs.unity3d.com/uploads/Main/monobehaviour_flowchart.svg
**URL to the documentation page (if already existing):**

**Comment by Calinou** [comment] 2020-07-13 10:21
Duplicate of #3475.

**Closed by Calinou** 2020-07-13 10:21 UTC
Labels: enhancement
