### ISSUE TITLE
Signals page is a point of disconnect

### ISSUE THREAD

**Issue by prominentdetail** [godotengine/godot-docs#2428] opened 2019-05-03 01:32 UTC
The signals page contains a big hole. It doesn't describe how to setup the Bullet scene. As a new user trying to start at the top and work my way through the guide, this is a point where I could very well give up due to frustration/uncertainty. I don't want to skip ahead in the guide, because usually that can result in overlooking something important.
From what I can gather, it seems like I need to use a kinematicbody and attach a script to it with a velocity variable inside it, and then do something with the velocity. None of this is explained though, so the example shown on the page leaves too many questions as to how to get that to work- all I can get is just a sprite spawning another sprite with a rotation relative to the mouse when clicking, but nothing moves.
The impression I get is that the rest of the guide will be just as incomplete as what I have come across now. This is a point where new users will stop and go elsewhere.

**Comment by clayjohn** [comment] 2019-05-03 02:21
What would you suggest to do to make it clearer?

**Comment by cbscribe** [comment] 2019-05-03 02:27
Duplicate of #2247 

Plan is to move bullet example to a separate complete tutorial. I'm in-progress on that change.

**Closed by cbscribe** 2019-05-03 02:27 UTC

**Comment by prominentdetail** [comment] 2019-05-03 03:36
@clayjohn I would probably refrain from using examples that involve stuff that hasn't been explained/taught/etc. There are probably other ways to illustrate the signals without having to resort to a complicated example.
