### ISSUE TITLE
OS.has_feature() is lacking correct link to Feature Tags in the current stable version

### ISSUE THREAD

**Issue by AniMerrill** [godotengine/godot-docs#4420] opened 2020-12-02 04:41 UTC
**Your Godot version:**
3.2.3 stable x11 64-bit

**Issue description:**
I was looking at the editor documentation for the function `OS.has_feature()` and saw a link to a supposed link of Feature Tags ([here](https://docs.godotengine.org/en/latest/getting_started/workflow/export/feature_tags.html)). Clicking it goes to the Godot Docs 404 page, and it's also listed on the website version of the docs. It looks like in the latest documentation the link has actually been updated to [this](https://docs.godotengine.org/en/latest/tutorials/export/feature_tags.html), however in the stable version this page doesn't seem to exist.

**URL to the documentation page:**
[OS.has_feature()](https://docs.godotengine.org/en/stable/classes/class_os.html#class-os-method-has-feature) , and here is the url to those [Feature Tags](https://docs.godotengine.org/en/latest/getting_started/workflow/export/feature_tags.html) as it appears directly in the documentation for that method.

**Comment by Calinou** [comment] 2021-01-31 17:28
Duplicate of https://github.com/godotengine/godot-docs/issues/4396 (same cause).

**Closed by Calinou** 2021-01-31 17:28 UTC
Labels: bug
