### ISSUE TITLE
Three problems

### ISSUE THREAD

**Issue by Lutalli** [godotengine/godot-docs#2466] opened 2019-05-18 04:25 UTC
### Problem I
In the table _Example Exec Flags_ in [article](https://docs.godotengine.org/en/3.1/getting_started/editor/external_editor.html) `Docs > Editor manual > Using an external text editor`, the flags of Visual Studio Code should be
```
{project} --goto {file}:{line}:{col}
```
or
```
{project} -g {file}:{line}:{col}
```
(There're similar problems in the other three flags, i.e., symbol `–` must be `-`) 

### Problem II
When reading the docs, it seems to be like this:
![image](https://user-images.githubusercontent.com/47910890/57964340-8b2b3300-7966-11e9-881c-5debef103aaa.png)
\- which shows that a strange empty area appears on the right of the page.
I tried the devtool, found that there was a css property:
```css
.wy-nav-content {
    padding: 1.618em 3.236em;
    height: 100%;
    max-width: 800px;
    margin: auto;
}
```
and I deleted `max-width: 800px;`, the page looked much better (in my opinion):
![image](https://user-images.githubusercontent.com/47910890/57964393-769b6a80-7967-11e9-861d-2ce4fccbf455.png)
![image](https://user-images.githubusercontent.com/47910890/57964405-a0ed2800-7967-11e9-8f0f-b2227973ecb8.png)

### Problem III
I think we can add a _scroll bar_ into the nav on the left of the page. That's because, the list of API is so long, that if I want to check `Viewport` (almost at the end of the list) for example, I need to roll my middle mouse button for a long time to reach it. A scroll bar can make us more pleasant.
![image](https://user-images.githubusercontent.com/47910890/57977938-212d8f00-7a35-11e9-8c42-546d0445f0e4.png)

---
I love Godot, for it's really easy for me to learn and use. The editor is pretty cool as well. So I hope the points above can be improved, thanks!

**Comment by Calinou** [comment] 2019-05-18 12:02
As for point II, the width of the page being limited is intentional. Long lines are difficult to read for humans; it's best to keep lines between 45 and 80 characters.

**Comment by volzhs** [comment] 2019-05-18 12:26
I prefer not to use `max-width`.
let users browser do it for their preference.

**Comment by Lutalli** [comment] 2019-05-18 12:30
@Calinou @volzhs Thanks for your replies!
After considering for a while, I reckon the center way is the best way (as many websites do this).

**Comment by akien-mga** [comment] 2019-06-11 08:58
"Problem I" is a duplicate of #2336.

In the future, please open one issue for each separate concern.

**Closed** 2020-02-13 04:57 UTC
