### ISSUE TITLE
The documentation for the ImmediateMesh

### ISSUE THREAD

**Issue by achu94** [godotengine/godot-docs#8257] opened 2023-10-16 21:20 UTC
**4.1.1.stable**

**Issue description:**
The documentation for the ImmediateMesh class is currently lacking sufficient information, making it challenging for users to work effectively with this class in Godot. Additionally, the error message provided in the documentation example may not be informative enough to assist users in troubleshooting common issues.

**Description Addition:**
I would also add in the description that the documentation does not explain how to add the instance as a child. The lack of information on how to correctly integrate ImmediateMesh instances as child nodes within a scene hinders users' understanding of how to incorporate this element effectively.

**URL to the documentation page (if already existing):**
 https://docs.godotengine.org/en/stable/tutorials/3d/procedural_geometry/immediatemesh.html

**Comment by clayjohn** [comment] 2023-10-18 21:59
This is indeed a problem. It has been reported several times already, so I will close this issue as a duplicate of https://github.com/godotengine/godot-docs/issues/7172

**Closed by clayjohn** 2023-10-18 21:59 UTC
Labels: enhancement, area:manual
