### ISSUE TITLE
Using axis instead of four condition

### ISSUE THREAD

**Issue by Watynecc** [godotengine/godot-docs#4889] opened 2021-05-03 16:06 UTC
**Your Godot version:**
3.3.stable.mono.official
**Issue description:**
Using this code PS: i use C#
velocity.x = Input.GetActionStrength("ui_right") - Input.GetActionStrength("ui_left"); velocity.y = Input.GetActionStrength("ui_down") - Input.GetActionStrength("ui_up");
instead of this code

if (Input.IsActionPressed("ui_right"))
{
    velocity.x += 1;
}

if (Input.IsActionPressed("ui_left"))
{
    velocity.x -= 1;
}

if (Input.IsActionPressed("ui_down"))
{
    velocity.y += 1;
}

if (Input.IsActionPressed("ui_up"))
{
    velocity.y -= 1;
}

Why :
It does the same result for less line
More easy to eat it (When learn Godot)
More minimal UwU
**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/getting_started/step_by_step/your_first_game.html#player-scene

**Comment by Calinou** [comment] 2021-05-03 16:19
I think this is done by design to avoid introducing the added complexity of `get_action_strength()` in a tutorial that targets beginners.

cc @NathanLovato

**Comment by NathanLovato** [comment] 2021-05-03 17:24
Yes, shorter is not necessarily easier for new users to understand. Anything you add, you need to explain. So here, you need to explain the new function is for analog input, that it has dead zones with joysticks, etc.

That's why we chose to go with plain conditions in this beginner-level tutorial.

**Comment by Watynecc** [comment] 2021-05-03 17:40
Oh okay i don't thinking about it situation
I don't even know what mean GetActionStriength() but that mean about if bouton is pressed or else is not pressed That normal variable declaration but _Delta make the work. That mean Update

That can be difficult to explain that for begeinner

**Comment by NathanLovato** [comment] 2021-05-03 19:39
Alright, seems that solves the issue, right? I'll close it. Let me know if you'd like to reopen it.

**Closed by NathanLovato** 2021-05-03 19:39 UTC
Labels: enhancement
