### ISSUE TITLE
Add documentation for GDExtension developers

### ISSUE THREAD

**Issue by pcting** [godotengine/godot-docs#7862] opened 2023-08-30 09:09 UTC
**Your Godot version:**
Godot 4.1+

**Issue description:**
I've been working on and off on building golang bindings for godot through GDExtension. It'll be nice to documentation geared towards GDExtension developers to reduce the barrier to entry for GDExtention development.

For example, here's a reddit post describing the exposed data types in the system: https://www.reddit.com/r/godot/comments/yja4ru/comment/iupp1b4/?utm_source=share&utm_medium=web2x&context=3

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/tutorials/scripting/gdextension/what_is_gdextension.html

**Comment by paddy-exe** [comment] 2023-08-30 09:29
Related to/Duplicate of https://github.com/godotengine/godot-docs/issues/5618

**Comment by Calinou** [comment] 2024-02-16 20:31
Thanks for the report! Consolidating in https://github.com/godotengine/godot-docs/issues/5618.

**Closed by Calinou** 2024-02-16 20:31 UTC
Labels: enhancement
