### ISSUE TITLE
this doesn't work. var velocity = Vector2.ZERO is always 0,0 and the bullets never move

### ISSUE THREAD

**Issue by whirlin22** [godotengine/godot-docs#8134] opened 2023-10-03 00:37 UTC
https://github.com/godotengine/godot-docs/blame/b861b68237f2710af919dcf8b4ad9a4189fe8ac1/tutorials/scripting/instancing_with_signals.rst#L33

**Comment by sandsalamand** [comment] 2023-10-03 05:11
Please follow the documentation issue format.

Are you following the example precisely in terms of where you're setting velocity = 0? If you set it in _physics_process, it won't move because the velocity will be reset to 0 on every tick.

**Comment by AThousandShips** [comment] 2023-10-03 14:04
Duplicate of https://github.com/godotengine/godot-docs/issues/7963

**Closed by AThousandShips** 2023-10-03 14:04 UTC
