### ISSUE TITLE
Always redirect user to latest docs

### ISSUE THREAD

**Issue by tavurth** [godotengine/godot-docs#3481] opened 2020-05-02 07:22 UTC
## **Your Godot version:**
3.2.1.stable.official

## **Issue description:**
When arriving from Google, I very often find myself on an outdated docs page.

I propose rewriting the users request to always point to the latest doc, unless that doc has significantly changed from the version the user is trying to access.

## Example:
1. I'd like to access the information about `InputMap`
2. I go to Google and type "Godot InputMap"
3. I arrive at the [3.1 docs page](https://docs.godotengine.org/en/3.1/classes/class_inputmap.html) and have to click through to the latest version every time.

At the moment this isn't much of an issue since the 3.1 and 3.2 docs are different colors, and I can tell that I need to redirect to get the latest docs.

## But what if I want the old docs?
If the previous page and the next page have vastly different modification times then it makes sense the user might want the old docs, as the Godot API may have changed by this time.

**Comment by pycbouh** [comment] 2020-05-02 09:07
This should already be fixed by #3422, but search engines will take time to update.

> since the 3.1 and 3.2 docs are different colors

Surely this banner is also indicative 🙂 
![image](https://user-images.githubusercontent.com/11782833/80859980-5692b300-8c6d-11ea-8639-32f990acc17b.png)

**Comment by tavurth** [comment] 2020-05-02 14:19
> This should already be fixed by #3422, but search engines will take time to update.
Great, glad to hear it!

> Surely this banner is also indicative 🙂
The links from google sometimes lead to a subheading or portion of the document, so this bar may not always be visible.

**Comment by mhilbrunner** [comment] 2020-05-02 20:55
Currently the plan is to always link to `/stable/` (so 3.2 currently) by default, not `/latest/`.
This should hopefully be the case after the latest changes we did are deployed everywhere and Google's index is refreshed.

So I'll close this as a duplicate of the issues mentioned in https://github.com/godotengine/godot-docs/pull/3422 for now. :) But thanks for taking the time to file an issue!

**Closed by mhilbrunner** 2020-05-02 20:55 UTC
Labels: bug
