### ISSUE TITLE
Custom Drawing 2d: Dynamic custom drawing error 

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-docs#151] opened 2016-05-20 17:15 UTC
Original issue by @mrbw85 on https://github.com/godotengine/godot/issues/4730

```
func wrap(value, minVal, maxVal):
        return (((value - minVal) % (maxVal - minVal)) + minVal)
```

does not want to take the float that delta represents in:
```
func _process(delta):
        angleFrom += rotAngle * delta
        angleTo += rotAngle * delta
        angleFrom = wrap(angleFrom, 0, 360)
        angleTo = wrap(angleTo, 0, 360)
        update()
```

gives error: Invalid operands 'float' and 'int' in operator '%'.
what syntax does
```
func wrap(value, minVal, maxVal):
        return (((value - minVal) % (maxVal - minVal)) + minVal)
```
need to be in order to accept delta value?

**Comment by 29jm** [comment] 2016-05-20 17:35
I think what you want is the fmod built-in math function, which can handle floats

**Comment by bojidar-bg** [comment] 2016-05-20 17:39
@akien-mga ~ The problem is that operator `%` works only on float-float or int-int values, but doesn't like mixing of types. (AFAIK).

So that should be:
````gd
return ((float(value - minVal) % float(maxVal - minVal)) + minVal)
````

**Comment by mrbw85** [comment] 2016-05-20 17:43
`func wrap(value, minVal, maxVal):`
>>	`var f1 = value - minVal`
>>	`var f2 = maxVal - minVal`
>>	`return fmod(f1, f2) + minVal`

This worked as well. Thank you.

**Comment by StraToN** [comment] 2016-05-20 18:26
Well, to be honest I wrote this wrap() function directly on Github, while I was at work (bad!). I had another function on my personal computer, which is a bit more trivial:
```
func wrap(value, min_value, max_value):
	if (value < min_value):
		return max_value-1
	if (value > max_value):
		return min_value+1
	return value
```

That is work-ish, but ugly and potentially incorrect. I'll correct the function wrap() in the tutorial to "cast" to float.

**Comment by StraToN** [comment] 2016-05-20 18:37
Reopening as wrapping the first angle value causes the whole angle to be returned. Il will debug this a bit later.

**Comment by independentCog** [comment] 2016-05-20 19:38
Was able to fix the alternation when it hit its peak by removing func wrap and just having:

`func _process(delta):`
>>`angleFrom += rotAngle * delta`
>>`angleTo += rotAngle * delta`  
>>`update()`
I haven't seen any enlargement and its been running on my machine for some time without crash. Values on monitor in debugger don't show any increase in memory. And process is fluctuating back and forth between the same values showing repetition.

**Comment by independentCog** [comment] 2016-05-20 20:49
This cropped into another question. When playing with it I was able to turn it into a timer/cooldown like object. I tried using set_process(false) outside a for statement with the delta adjustment in a loop and also inside an if statement. Both times it seemed the override was seen regardless and the process was stopped. How can I go about making this:

`func wrap(value, minVal, maxVal):`
`>>var f1 = value - minVal`
`>>var f2 = maxVal - minVal`
`>>return fmod(f1, f2) - minVal`

`func _process(delta):`
`>>angleFrom += rotAngle * (delta*2)` 
`>>angleFrom = wrap(angleFrom, 0, 360)`
`>>update()`

iterate only n times before disappearing?

**Comment by StraToN** [comment] 2016-05-20 20:49
@independentCog As I said in the tutorial, if you don't wrap angle values between 0 and 360, their value will increase indefinitely until they reach the maximum value the CPU is able to manage, causing Godot to act weirdly and/or crash. 
It will not cause any increase in memory at all, so it is absolutely normal you don't see any. Just remember that your CPU defines a maximum value for types: in the case of integer, it is 2^31-1.

Ok, you'll never reach such value unless you leave the program running for a very, very long time. Still, the problem exists and you just leave it unresolved. Just to let you know, spacecrafts crashed because of this kind or errors. So, in my humble opinion, it is a good thing to learn how to avoid such critical bugs.

**Comment by independentCog** [comment] 2016-05-20 20:58
I see. I thought I read that it increased in size and interpreted that as physical size of the object. I'm a skeptic by nature haha my bad.
The closest I got to it behaving with the wrapper was this:

`func wrap(value, minVal, maxVal):`
`>>var f1 = value - minVal`
`>>var f2 = maxVal - minVal`
`>>return fmod(f1, f2) + minVal`

`func _process(delta):`
`>>angleFrom += rotAngle * delta`
`>>angleTo += rotAngle * delta`  
`>>angleFrom = wrap(angleFrom, 70, 360)`
`>>angleTo = wrap(angleTo, 360, 70)`
`>>update()`

It maintains itself until it reaches apex than it flips to the position it was when the cycle first began.

**Comment by StraToN** [comment] 2016-05-20 21:00
@independentCog I just updated the tutorial. We needed a simple 'if' statement. I think it is resolved now, closing ;) Thanks for reporting!

**Closed by StraToN** 2016-05-20 21:00 UTC
