### ISSUE TITLE
3 links in ui_introduction_to_the_ui_system tutorial are not working as expected.

### ISSUE THREAD

**Issue by mrwanashraf** [godotengine/godot-docs#1578] opened 2018-07-08 17:32 UTC
in [ui_introduction_to_the_ui_system](http://docs.godotengine.org/en/3.0/getting_started/step_by_step/ui_introduction_to_the_ui_system.html) tutorial there are 3 links that don't redirect to the correct path.

first link:
[Build your first game UI in Godot.](http://docs.godotengine.org/en/3.0/getting_started/step_by_step/ui_introduction_to_the_ui_system.html#) redirects to the same page.

second link: 
[Advanced UI nodes and Themes.](http://docs.godotengine.org/en/3.0/getting_started/step_by_step/img/#) redirects to `  SORRY This page does not exist yet. ` 

third link:
[Design advanced UI with other Control nodes.](http://docs.godotengine.org/en/3.0/getting_started/step_by_step/img/#)  redirects to `  SORRY This page does not exist yet. `

**Comment by FeralBytes** [comment] 2018-07-31 21:40
This is a duplicate of #1379 
First Link works in latest. 
Second link was removed in latest.
Third link is shortened and now points to the GUI index.
These issues were patched by d98bb0d5c0b4c280b7e6e6e4d0aa3bf6e5c608f0 
Recommend closing.

**Closed** 2018-08-02 17:13 UTC
