### ISSUE TITLE
3.2 branch downloadable format (pdf, epub)

### ISSUE THREAD

**Issue by veermetri05** [godotengine/godot-docs#3459] opened 2020-04-27 16:18 UTC
**Your Godot version:**
3.2
**Issue description:**
There is no download option for the 3.2 branch documentation. There are available for previous branch .
**URL to the documentation page (if already existing):**
https://readthedocs.org/projects/godot/downloads/

**Comment by clayjohn** [comment] 2020-04-27 16:20
I think that is something that read the docs used to provide but they don't anymore because of slow build times.

**Comment by akien-mga** [comment] 2020-04-27 16:40
I disabled them myself as it makes the builds too slow, and we often time out.
They're also not very convenient formats for using documentation meant to be viewed in HTML - much better would be a zip of the HTML docs, but RTD doesn't provide this option yet: https://github.com/readthedocs/readthedocs.org/issues/4190

**Comment by clayjohn** [comment] 2020-04-27 16:51
For that, @Calinou provides html builds on his godot builds website https://hugo.pro/projects/godot-builds/ However, his builds track latest rather than stable

**Comment by Calinou** [comment] 2020-04-27 18:21
@clayjohn We can upload the Travis CI builds somewhere using its deployment feature, so it can be downloaded easily as a ZIP archive.

**Comment by Calinou** [comment] 2020-04-27 19:38
Also, this is a duplicate of #3149, so I'll close this.

**Closed by Calinou** 2020-04-27 19:38 UTC
Labels: enhancement
