### ISSUE TITLE
OS.has_feature documentation has a broken link to the Feature Tags page

### ISSUE THREAD

**Issue by Exerionius** [godotengine/godot-docs#5461] opened 2021-12-22 13:43 UTC
**Your Godot version:** 3.4

**Issue description:** broken link

**URL to the documentation page:** https://docs.godotengine.org/en/stable/classes/class_os.html#class-os-method-has-feature

Currently (3.4 stable) the link in the question is https://docs.godotengine.org/en/3.4/getting_started/workflow/export/feature_tags.html while it should be https://docs.godotengine.org/en/stable/getting_started/workflow/export/feature_tags.html

**Comment by Calinou** [comment] 2021-12-22 22:08
Duplicate of https://github.com/godotengine/godot-docs/issues/4396 (same cause).

**Closed** 2021-12-22 22:08 UTC
Labels: bug, class reference
