### ISSUE TITLE
Outdated information in "Your first 2D game" guide

### ISSUE THREAD

**Issue by pfiffli** [godotengine/godot-docs#7892] opened 2023-09-08 12:39 UTC
Version 4.1

At the very start of the section "creating the enemy" of the guide "Your first 2d game" there is mention of `CollisionObject2D` which seems to have been replaced by `CollisionShape2D` in newer versions.

This leads to confusion and a bug since `CollisionShape2D` doesn't possess a `Mask` property.

URL:
https://docs.godotengine.org/en/stable/getting_started/first_2d_game/04.creating_the_enemy.html

**Comment by AThousandShips** [comment] 2023-09-08 12:45
It doesn't refer to the same thing, see the description:
> In the RigidBody2D properties

**Comment by AThousandShips** [comment] 2023-09-08 12:48
Duplicate of https://github.com/godotengine/godot-docs/issues/6885

**Closed by AThousandShips** 2023-09-08 12:48 UTC
Labels: bug
