### ISSUE TITLE
"ProjectSetting" properties display incorrectly on mobile

### ISSUE THREAD

**Issue by radlotus** [godotengine/godot-docs#7764] opened 2023-08-02 14:58 UTC
Some doc pages display incorrectly on mobile and allow zooming outside the content.

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/classes/class_projectsettings.html

https://docs.godotengine.org/en/stable/classes/class_navigationpathqueryparameters2d.html

![Screenshot_2023-08-02-17-57-40-543_com android chrome](https://github.com/godotengine/godot-docs/assets/95962222/4ac55ed4-5387-452b-b197-062e63704fcc)

**Comment by AThousandShips** [comment] 2023-08-02 15:05
Duplicate of #7504

**Closed by AThousandShips** 2023-08-02 15:05 UTC
Labels: bug
