### ISSUE TITLE
WebSocket Page Outdated Information

### ISSUE THREAD

**Issue by hunterbk** [godotengine/godot-docs#8676] opened 2023-12-23 19:20 UTC
**Your Godot version:**
Godot v4.2 Stable
**Issue description:**
The [WebSocket](https://docs.godotengine.org/en/stable/tutorials/networking/websocket.html) page is not up to date. There is a block of code using beta Godot 4 code or maybe even 3.x code, the code references classes that don't even exist anymore, and @export just says export
**URL to the documentation page:**
https://docs.godotengine.org/en/stable/tutorials/networking/websocket.html

**Comment by AThousandShips** [comment] 2023-12-23 19:26
This page is listed as out of date, so this is known 🙂

**Comment by AThousandShips** [comment] 2023-12-23 19:29
Duplicate of https://github.com/godotengine/godot-docs/issues/6631

**Closed by AThousandShips** 2023-12-23 19:29 UTC
Labels: bug
