### ISSUE TITLE
Android Export Fails: 'apksigner' returned with error #1

### ISSUE THREAD

**Issue by JohnCWakley** [godotengine/godot-docs#4796] opened 2021-03-31 13:14 UTC
**Your Godot version:**
v3.3.rc7.official

**Issue description:**
I followed the documentation page (URL below) to setup for Android Exports. When attempting to export to Android, I received the following error: **'apksigner' returned with error #1**

From the command-line, I ran apksigner and received the following error:
```
$ ./apksigner.bat
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/android/apksigner/ApkSignerTool has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)
```

During my investigation, I discovered that build-tools;30.0.1 requires JDK 9. For testing, I ran the following:
```
$ sdkmanager.bat --uninstall "build-tools;30.0.1"
$ sdkmanager.bat --install "build-tools;29.0.3"
$ ./apksigner.bat
USAGE: apksigner <command> [options]
       apksigner --version
       apksigner --help
```

**Solution:**
Uninstall build-tools 30.0.1 and install build-tools 29.0.3.
Also, the doc page below should be updated to use build-tools 29.0.3.

**This issue, and it's solution, works on both Windows 10 and Linux (Solus 4.2)**

**URL to the documentation page:**
[https://docs.godotengine.org/en/latest/tutorials/export/exporting_for_android.html#doc-exporting-for-android](https://docs.godotengine.org/en/latest/tutorials/export/exporting_for_android.html#doc-exporting-for-android)

**Comment by m4gr3d** [comment] 2021-04-01 22:23
@JohnCWakley Thanks for reporting the issue and providing a solution! Which version of the jdk do you have installed on your machine that was causing the issue?

**Comment by JohnCWakley** [comment] 2021-04-01 22:45
> @JohnCWakley Thanks for reporting the issue and providing a solution! Which version of the jdk do you have installed on your machine that was causing the issue?

@m4gr3d You're very welcome! I followed the doc page (linked in my first post) OpenJDK link to [https://adoptopenjdk.net/index.html?variant=openjdk8&jvmVariant=hotspot](https://adoptopenjdk.net/index.html?variant=openjdk8&jvmVariant=hotspot) and selected OpenJDK 8 (LTS) and HotSpot. The version (at the time) is `jdk8u282-b08`.

I am sure this is not a bug in the Godot code, but rather an update to the doc page to use `build-tools;29.0.3`.

If you need any other information, please let me know. :smiley:

-John

**Comment by allkhor** [comment] 2021-04-23 16:37
Update build-tools to 30.0.3 solved this issue!

**Comment by mshka** [comment] 2021-04-24 01:22
on windows I was getting `'apksigner' returned with error #1` and I downgraded to `29.0.3.` and now I get `'apksigner' returned with error #2`

**Comment by maciejbudzyn** [comment] 2021-04-24 13:18
> 
> 
> on windows I was getting `'apksigner' returned with error #1` and I downgraded to `29.0.3.` and now I get `'apksigner' returned with error #2`

Try to update android build tools to 30.0.3, it solved my problems.
If it won't help then try to start godot with "--verbose" argument, this should give you some more logs on console windows, together with the problem root cause. 

I think that if build tools are below 30.0.0 , the apksigner complains about keystore format, if there are above 30.0.0 but below 30.0.3 it complains about java versions.

**Comment by groug** [comment] 2021-04-25 08:19
Hi,

I followed the doc 100% (cmdline-tools, openjdk 8, dbug key generation with deststoretype override)  to build an android export with godot headless on a pristine server.

Same export error, the verbose mode gave the same apksigner error.
Downgraded to 29.0.3 and it now works! Thanks for the tip.
Didn't try to upgrade java as the doc seems categorical on the need to use jdk 8

If openjdk should be upgraded or build tools downgraded, the doc should be updated accordingly

**Comment by groug** [comment] 2021-04-25 08:21
both are mentioned: 29.0.3 and 30.0.3. was is a typo or is 30.0.3 the best version to use?

**Comment by maciejbudzyn** [comment] 2021-04-25 13:18
> 
> 
> both are mentioned: 29.0.3 and 30.0.3. was is a typo or is 30.0.3 the best version to use?

30.0.3 with the newest available jdk should work.

**Comment by JohnCWakley** [comment] 2021-04-26 14:21
> > both are mentioned: 29.0.3 and 30.0.3. was is a typo or is 30.0.3 the best version to use?
> 
> 30.0.3 with the newest available jdk should work.

I have not tried the newest JDK yet (including 30.0.3) - I will give it a try as soon as I get a chance...

**Comment by JohnCWakley** [comment] 2021-04-26 15:09
Update:

I followed the instructions at
[https://docs.godotengine.org/en/stable/getting_started/workflow/export/exporting_for_android.html#doc-exporting-for-android](https://docs.godotengine.org/en/stable/getting_started/workflow/export/exporting_for_android.html#doc-exporting-for-android)
but replaced `build-tools;30.0.1` with `build-tools;30.0.3` and my export worked perfectly!

Here's the updated sdkmanager command:
`sdkmanager --sdk_root=<android_sdk_path> "platform-tools" "build-tools;30.0.3" "platforms;android-29" "cmdline-tools;latest" "cmake;3.10.2.4988404" "ndk;21.4.7075529"`

The documentation should be updated to use `build-tools;30.0.3` and this ticket can be closed.
cc: @akien-mga

**Comment by akien-mga** [comment] 2021-04-27 16:49
Fixed by #4873.

**Closed by akien-mga** 2021-04-27 16:49 UTC
Labels: bug

**Comment by wombatwingdings** [comment] 2021-11-15 19:54
Had the same issue following recent pull & rebuild. I had correct Android SDK Built Tools as per Godot docs, but it was for some reason picking up an old version (as shown when running godot with --verbose). Uninstalling that version in the SDK Manager fixed it for me. Thanks!

**Comment by harbaum** [comment] 2024-03-18 15:46
I am seeing the same issue:

> ADDING: resources.arsc
> All located 'apksigner' tools in ~/Android/Sdk/build-tools failed to execute
> Starting signing of the APK binary using <FAILED>
> WARNING: Code Signing: All 'apksigner' tools located in Android SDK 'build-tools' directory failed to execute. Please check that you have the correct version installed for your target sdk version. The resulting APK is unsigned.
>      at: add_message (editor/export/editor_export_platform.h:179)
 
The odd thing is that i can easily sign manually:

> $ ~/Android/Sdk/build-tools/33.0.2/apksigner sign --ks ~/Android/debug.keystore ./Godot.apk 
> Keystore password for signer #1: 
> $ 

Afterward, the Godot.apk does indeed install.

So the tool is there and it is working. Invoking godot with --verbose does not give any additional hints.
