### ISSUE TITLE
Writing more applied tutorials

### ISSUE THREAD

**Issue by synalice** [godotengine/godot-docs#8421] opened 2023-11-08 08:16 UTC
I think the current documentation really lacks a section with tutorials of a more _"applied"_ nature. The closest equivalent for what I'm talking about is the `https://docs.godotengine.org/en/latest/tutorials/**` section, but it is more tailored towards the _"fundamental"_ knowledge about the concepts described there.

I am rather talking about thing like these: #3791. Where would you put this? This doesn't really fit into any category, but at the same time, it many come in handy to someone who tries to do just that.

One of the problems I see with keeping such things in the documentation, is that they may _"break"_ with updates, and it may happen a bit faster than everything else _(but then again, all documentation goes stale and needs to be revised with updates)_. There is already a banner that says that the current page hasn't yet been verified to work with a new version, so we can just use that.

Probably the best place for such kind of tutorials might be the [Godot's Q&A](https://ask.godotengine.org/), but it's currently dead and even then, I think it could have used [some improvements](https://meta.stackexchange.com/questions/2267/are-there-any-clones-alternatives-for-running-a-stack-exchange-style-qa-site).

**Comment by YuriSizov** [comment] 2023-11-08 09:40
This is by design. We believe community resources are the best place for practical tutorials and courses, and the official documentation should explain the basics. The only exception is the step by step guide.

**Comment by Calinou** [comment] 2023-11-08 13:46
> I am rather talking about thing like these: https://github.com/godotengine/godot-docs/issues/3791. Where would you put this? This doesn't really fit into any category, but at the same time, it many come in handy to someone who tries to do just that.

This can be put in the method description of `get_script()` in the class reference.

**Comment by skyace65** [comment] 2024-01-27 18:46
Closing per Calinou and  Yuri's comments. In addition you need to consider that if we were to expand the docs to add more specific tutorials than we did in the past that's an even larger maintenance burden, and it doesn't necessarily bring in more maintainers. The amount of open issues in the docs right now is extremely high, if we had applied tutorials in addition to what we have now I can't even being to image how many issues there would be.

And the fact is in an event like that we'd all be silly to focus time on keeping those tutorials up to date instead of manual pages. There are tons of talented youtube and website creators that handle specific topics out there, but there's only 1 manual.

**Closed by skyace65** 2024-01-27 18:46 UTC
Labels: enhancement, discussion
