### ISSUE TITLE
asteroids style control example not rotating

### ISSUE THREAD

**Issue by hlb-schmidt** [godotengine/godot-docs#1826] opened 2018-10-10 08:13 UTC
http://docs.godotengine.org/en/latest/tutorials/physics/physics_introduction.html#using-rigidbody2d has an example for asteroids style movement:

```
extends RigidBody2D

var thrust = Vector2(0, 250)
var torque = 20000

func _integrate_forces(state):
    if Input.is_action_pressed("ui_up"):
        set_applied_force(thrust.rotated(rotation))
    else:
        set_applied_force(Vector2())
    var rotation_dir = 0
    if Input.is_action_pressed("ui_right"):
        rotation_dir += 1
    if Input.is_action_pressed("ui_left"):
        rotation_dir -= 1
    set_applied_torque(rotation_dir * torque)
```

but in godot 3.1 nightly (from https://hugo.pro/projects/godot-builds/) on ms-windows 7 my RigidBody2D wont turn.

i also tried `add_torque(rotation_dir * torque)` and `apply_torque_impulse(rotation_dir * torque)` but no rotation happens. _(fwiw, `set_applied_force` does work)_

dunno if problem is in this snippet, godot or my scene:

- project-settings: general -> physics -> 2d -> default gravity 0 _(so the player wont keep falling "down")_
- RigidBody2D _(has the above script)_
  - Sprite _(the godot icon.png)_

> ps. the forward movement in this example stops after a while (press ui_up once, and the movement stops after a while), i thought asteroids style kept the momentum forever?

**Comment by hlb-schmidt** [comment] 2018-10-10 10:00
ah! seems `set_applied_torque` needs a CollisionShape2D?

cause with this scene, rotation works:
- RigidBody2D _(has the above script)_
  - CollisionShape2D
  - Sprite _(the godot icon.png)_

i leave this issue open, just in case this is not the correct behaviour. (that `set_applied_torque` needs CollisionShape2D but `set_applied_force` does not)

**Comment by pwab** [comment] 2018-10-11 14:44
To work properly a RigidBody (2d and 3d) needs a shape. This is stated in the tooltip when creating a RigidBody node:
![warning](https://user-images.githubusercontent.com/19271185/46811316-ccc18300-cd72-11e8-9355-b5b1f5fb6525.png)

I'm not familiar with the code base but I'm pretty sure that `set_applied_force` works with a RigidBody without a CollisionShape because a RigidBody always has a mass. Then the reaction to an applied force (the acceleration of the body) is calculated by `a = F / m`.

In contrast the function `set_applied_torque` needs a moment of inertia to calculate the angular acceleration of the body and this moment depends on the shape of the body (area in 2d, volume in 3d space). So it is inevitable that the RigidBody has a CollisionShape if a torque should be set. This also applies to `add_torque` and `apply_torque_impulse`.

But I tried to search these information in the docs and was also a bit confused how it is structured in regard to RigidBodies. Maybe the part [here](http://docs.godotengine.org/en/latest/tutorials/physics/physics_introduction.html#rigid-body-modes) and the page [here](http://docs.godotengine.org/en/latest/tutorials/physics/rigid_body.html#rigid-body) need more information.

**Comment by Calinou** [comment] 2021-08-06 19:52
This is likely resolved in the latest version of the documentation, closing. Please comment if you can still reproduce 
this.

**Closed by Calinou** 2021-08-06 19:52 UTC
