### ISSUE TITLE
Please improve the documentation search

### ISSUE THREAD

**Issue by marcotrosi** [godotengine/godot-docs#10278] opened 2024-11-17 11:48 UTC
Hello Team Godot,

we again had the issue in our Godot group that we wanted to help a user, but the search engine of the Godot documentation site makes it sometimes hard for us to quickly find what we need.

For example I just wanted to find the documentation for the `lerp` function, it shows all kinds of things but not the documentation for that function.

I would expect that the first three entries are ...
- https://docs.godotengine.org/en/stable/classes/class_%40globalscope.html#class-globalscope-method-lerp
- https://docs.godotengine.org/en/stable/classes/class_vector2.html#class-vector2-method-lerp
- https://docs.godotengine.org/en/stable/classes/class_vector3.html#class-vector3-method-lerp

or that there is a function reference with all functions only, so that we can use the browser search

or that the search can be made more precise, like "func: lerp"

or that each occurrence of the word "lerp" in the code examples would be a link to the documentation of the used function.

anything is fine, but as it is today it's not okay, the search is currently not practical.

Thank you very much

keep up the great work, sending love

--marco

**Comment by mhilbrunner** [comment] 2024-11-17 13:07
Hey and thank you! This is a duplicate of https://github.com/godotengine/godot-docs/issues/9646, so I'm going to close it, however having these specific examples is certainly helpful.

For anyone reading this, if you run into any specific broken search cases, report them in the above issue, please.

**Closed by mhilbrunner** 2024-11-17 13:07 UTC
Labels: enhancement

**Comment by marcotrosi** [comment] 2024-11-17 14:16
thank you so much @mhilbrunner ❤
I will add my comment there
