### ISSUE TITLE
Godot 4 documentation still references old comment syntax for "warning-ignore"

### ISSUE THREAD

**Issue by Mercerenies** [godotengine/godot-docs#8164] opened 2023-10-05 15:05 UTC
**Your Godot version:**

Godot 4.1.1.stable.official

**Issue description:**

The Godot documentation on the GDScript warning system still says

> To ignore specific warnings in one file, insert a special comment of the form `# warning-ignore:warning-id`, or click on the ignore link to the right of the warning's description. Godot will add a comment above the corresponding line and the code won't trigger the corresponding warning anymore:

As far as I can tell, such comments no longer have any effect on Godot. Instead, the "Ignore" button in the IDE adds an annotation of the form `@warning_ignore("warning_id")` above the warning, not a comment. The documentation should be updated to reflect the new syntax for locally suppressing warnings. There is also a screenshot of the editor on that page which will need to be updated as well, as it uses the old syntax.

**URL to the documentation page:** https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/warning_system.html

**Comment by AThousandShips** [comment] 2023-10-05 15:21
Duplicate of https://github.com/godotengine/godot-docs/issues/8145

**Closed by AThousandShips** 2023-10-05 15:21 UTC
Labels: bug
