### ISSUE TITLE
3-to-4 Conversion Guide

### ISSUE THREAD

**Issue by daveTheOldCoder** [godotengine/godot-docs#6218] opened 2022-09-25 00:51 UTC
There is a need for a comprehensive guide for converting a Godot 3.x project to 4.x.

The existing project converter (https://github.com/godotengine/godot/blob/master/editor/project_converter_3_to_4.cpp) does a lot of the work, but it can't handle everything.

Is such a document already being written?

Is there a plan to create such a document?

**Comment by Calinou** [comment] 2022-09-25 01:31
Duplicate of https://github.com/godotengine/godot-docs/issues/4960.

**Closed by Calinou** 2022-09-25 01:31 UTC
Labels: enhancement
