### ISSUE TITLE
Goodot Persian translator

### ISSUE THREAD

**Issue by mitsuha-miamizu** [godotengine/godot-docs#4014] opened 2020-09-15 05:22 UTC
**Your Godot version:3.2**

**Issue description:Persian translation of Godot document**

**URL to the documentation page (if already existing):https://docs.godotengine.org/en/stable/**

**Comment by akien-mga** [comment] 2020-09-15 05:56
Duplicate of #4013.

**Closed by akien-mga** 2020-09-15 05:56 UTC
Labels: enhancement
