### ISSUE TITLE
OptionButton signals section is misleading, implementation is also not useful

### ISSUE THREAD

**Issue by Kamineko7** [godotengine/godot-docs#2548] opened 2019-06-20 22:43 UTC
**OptionButton**
https://docs.godotengine.org/en/3.1/classes/class_optionbutton.html
> 
>     item_selected ( int ID )
> 
> This signal is emitted when the current item was changed by the user. Index of the item selected is passed as argument.

While the description is true, the default argument when creating this signal connection (and in docs) is **ID**, not **IDX**. The other signal available also states:

>     item_focused ( int ID )
> 
> This signal is emitted when user navigated to an item using ui_up or ui_down action. ID of the item selected is passed as argument.

Passing index instead of ID defeats the purpose of using IDs. Getting ID back from index using _item_selected_ requires reference to the instance or creating lookup dictionary, which again makes usage of signals less useful. There is no reason I can see why _item_focused_ returns the ID but _item_selected_ doesn't.

**Comment by bojidar-bg** [comment] 2019-07-02 16:53
Duplicate of https://github.com/godotengine/godot/issues/25273?

**Comment by Calinou** [comment] 2020-02-26 10:46
Is this still relevant in Godot 3.2?

**Comment by Calinou** [comment] 2020-07-30 10:01
This was likely resolved by https://github.com/godotengine/godot/pull/25422, closing.

**Closed by Calinou** 2020-07-30 10:01 UTC
