### ISSUE TITLE
Error reading the ePub version of the documentation

### ISSUE THREAD

**Issue by Bruce200** [godotengine/godot-docs#3882] opened 2020-08-08 17:51 UTC
**Your Godot version:**
I have found this problem in both the 3.2 and stable download

**Issue description:** 
When attempting to read the file in the Overdrive app on a Kindle Fire, I am confronted with this on pages past the "Instancing" chapter (as far as I can tell):
```
This page contains the following errors:

error on line 30 at column 1352: Opening and ending tag mismatch: meta line 0 and head

Below is a rendering of the page up to the first error:
```
Below this, nothing shows up.

**URL to the documentation page (if already existing):**
I'm not sure what this problem entails, so I don't what page to put down.

**Comment by clayjohn** [comment] 2020-08-08 21:06
Duplicate of https://github.com/godotengine/godot-docs/issues/3862

Please search existing issues before opening a new issue.

**Closed by clayjohn** 2020-08-08 21:06 UTC
Labels: bug
