### ISSUE TITLE
Discrepency between TabBar tab index type in Docs and C#

### ISSUE THREAD

**Issue by QuatschVirus** [godotengine/godot-docs#8012] opened 2023-09-23 08:31 UTC
**Your Godot version:**
4.1.1

**Issue description:**
Documentation for `TabBar` shows the argument type for signals to be an `int`, is a `long` in C# (tested for tab_changed and tab_clicked)

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/classes/class_tabbar.html#signals

If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

**Comment by AThousandShips** [comment] 2023-09-23 08:34
Duplicate of https://github.com/godotengine/godot/issues/65749

**Closed by AThousandShips** 2023-09-23 08:34 UTC
Labels: bug
