### ISSUE TITLE
Physics interpolation tutorial in the french documentation mention a setting that has not been implemented yet.

### ISSUE THREAD

**Issue by Tetane** [godotengine/godot-docs#7696] opened 2023-07-20 09:45 UTC
**Your Godot version:**
4.1

**Issue description:**
The part of the documentation that explains physics interpolation says to turn on `physics/common/physics_interpolation` but this setting currently does nothing. This seems to be only an issue with the french documentation, because those pages do not exist in the english documentation.

**URL to the documentation page:**
https://docs.godotengine.org/fr/stable/tutorials/physics/interpolation/index.html
https://docs.godotengine.org/fr/stable/classes/class_projectsettings.html#class-projectsettings-property-physics-common-physics-interpolation

**Comment by AThousandShips** [comment] 2023-07-20 09:55
The translated documentation is for 3.x, the 4.x documentation hasn't been translated yet, the pages are incorrectly showing "stable" when it matches 3.x

**Comment by AThousandShips** [comment] 2023-07-20 10:04
Duplicate of #7233

**Closed by AThousandShips** 2023-07-20 10:04 UTC
Labels: bug
