### ISSUE TITLE
MeshInstance.get_active_material() mentioned in docs, but does not exist in-engine.

### ISSUE THREAD

**Issue by drwhut** [godotengine/godot-docs#4619] opened 2021-02-02 23:24 UTC
**Your Godot version:**
Godot 3.2.3 Stable

**Issue description:**
I've been working on a bug caused by materials for my project, and I noticed while looking at the documentation for the `MeshInstance` class, there was a method called `get_active_material`. I tried to use this method in my game, but an error came up saying it was not a method for the class - I then checked the in-editor documentation to see if it was mentioned there, and it wasn't.

**URL to the documentation page:**
[MeshInstance.get_active_material](https://docs.godotengine.org/en/stable/classes/class_meshinstance.html#class-meshinstance-method-get-active-material)

**Comment by pycbouh** [comment] 2021-02-02 23:46
This method was added in godotengine/godot#40313 and is part of the 3.2.4 release, which will soon be released as stable (you can try [a release candidate](https://godotengine.org/article/release-candidate-godot-3-2-4-rc-1) for it). The docs are already synced, ahead of time.

**Comment by Calinou** [comment] 2021-02-03 00:26
Duplicate of https://github.com/godotengine/godot-docs/issues/4616 (same cause).

**Closed by Calinou** 2021-02-03 00:26 UTC
Labels: bug
