### ISSUE TITLE
File name naming conventions inconsistent with engine default file names

### ISSUE THREAD

**Issue by ShatReal** [godotengine/godot-docs#4602] opened 2021-01-30 15:00 UTC
**Your Godot version:**
3.2.4-rc1
**Issue description:**
The GDScipt style guide reads:

> Use snake_case for file names.

But when you click on the script icon in the editor, the default name is the same as the node's name, which should be in PascalCase. This is inconsistent.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/gdscript_styleguide.html#file-names

**Comment by Calinou** [comment] 2021-01-30 15:01
Duplicate of https://github.com/godotengine/godot-proposals/issues/1211.

**Closed by Calinou** 2021-01-30 15:01 UTC
Labels: enhancement
