### ISSUE TITLE
PopupMenu Signals function variable type being incorrect in docs

### ISSUE THREAD

**Issue by qngg** [godotengine/godot-docs#8637] opened 2023-12-17 04:04 UTC
**Your Godot version:**
Godot v4.2 C# Mono

**Issue description:**
PopupMenu Signals function variable type being incorrect in docs. In the docs, signals were said to have int type variables however it actually accepts long instead. This includes the id_pressed() function, id_focused function & the index_pressed() function. (srry for bad english)

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/classes/class_popupmenu.html#signals

**Comment by AThousandShips** [comment] 2023-12-17 09:49
Duplicate of https://github.com/godotengine/godot-docs/issues/8621

**Closed by AThousandShips** 2023-12-17 09:49 UTC
Labels: bug
