### ISSUE TITLE
Debugging section

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-docs#988] opened 2018-01-19 13:16 UTC
We have a couple issues on this topic already focusing on single aspects (#173, #298, #368)

I think we could have a complete "Debugging" main section with the following structure:
- Debugging in Godot
  * Overview of debugging tools
  * Using the Godot debugger (#298)
  * Remote debugging (#173)
  * Common error codes (#368)
  * Using the profiler
  * more?
- Platform-specific debugging
  * Debugging X11 and macOS (gdb, checking console output, etc.)
  * Debugging Windows (windbg, checking OpenGL support, etc.)
  * Debugging Android (adb, etc.)
  * Debugging iOS (how?)
  * Debugging HTML5 (web console, check webgl support, etc.)
  * Debugging UWP (how?)

WDYT about this structure and the proposed sub-sections and pages?

**Comment by reduz** [comment] 2018-01-19 13:19
sounds good, for mobile (well, Android mostly) it would be nice to put
emphasis on the remote filesystem, which works very nicely

**Comment by eon-s** [comment] 2018-01-19 13:25
If I remember right, the debugger may get more changes on 3.1, so probably will be better to do the platform-specific section first and maybe the error codes (if these are not improved in the engine), leaving the debugging tools to make after the debugger update or not wasting too much time on current ones, just an overview.

**Comment by mhilbrunner** [comment] 2018-01-20 08:59
Also, debugging C# vs GDScript, now that C# is an official option.

**Comment by mhilbrunner** [comment] 2018-03-13 18:31
Closing as duplicate of https://github.com/godotengine/godot-docs/issues/368 for now.

**Closed by mhilbrunner** 2018-03-13 18:31 UTC
Labels: enhancement, help wanted
