### ISSUE TITLE
Minor visual bug on a docs page "Using the Asset Library"

### ISSUE THREAD

**Issue by zddautenhahn0214** [godotengine/godot-docs#8987] opened 2024-02-17 15:04 UTC
**Your Godot version:**
Was not in Godot I was on google chrome. 1920x1080 monitor windows 10

**Issue description:**
I am a beginner and was looking up how to use the asset library when I went the the page and could not read it.
Refreshing did not fix it.
I opened inspect element to see if I could do a workaround and it then fixed itself and remained fixed even after refreshing the page.
I was able to recreate the issue by opening the link again in a new tab.
I did not have the same issue on my phone.

Not a significant issue as I can get around it, still wanted to report it so that it is known

Here is the google search I did and the link I then clicked
![image](https://github.com/godotengine/godot-docs/assets/61391672/17bc65c2-5fa9-4692-b460-71214dd075ec)

This is what I initially saw
![image](https://github.com/godotengine/godot-docs/assets/61391672/cc625a37-26e3-4048-8947-74b3a771acb2)

I open inspect element
![image](https://github.com/godotengine/godot-docs/assets/61391672/3c63f11d-31a8-4a7e-ac93-87b7a5a67996)

I close inspect element
![image](https://github.com/godotengine/godot-docs/assets/61391672/0c0e74ea-ff6e-4996-a53f-8a1ed79e609e)

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/community/asset_library/using_assetlib.html#:~:text=When%20you%20click%20on%20an,it%20using%20the%20Retry%20button.

If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

**Comment by AThousandShips** [comment] 2024-02-17 15:09
Duplicate of https://github.com/godotengine/godot-docs/issues/4790

**Closed by AThousandShips** 2024-02-17 15:09 UTC
Labels: bug
