### ISSUE TITLE
Cannot view C# code snippets

### ISSUE THREAD

**Issue by BlueStaggo** [godotengine/godot-docs#4787] opened 2021-03-28 09:08 UTC
**Your Godot version:**
at least stable / 3.3 / 3.2

**Issue description:**
I wanted to learn Godot for the third time, but this time with C#. I remembered some things, so I skipped over to the Scripting tutorial. In the code snippets in any section, you can have a choice of language: GDScript or C#. However, when I went to click the button to switch to C#, it did nothing; it was stuck on GDScript. I wanted to use C# because there weren't any other good game engines I can find (no, I can't get Unity). What I had to do was go onto the [Wayback Machine](http://web.archive.org/web/*/docs.godotengine.org/en/stable/getting_started/step_by_step/scripting.html) and select the latest snapshot to make it work. When I went onto the next tutorial (Scripting (continued)), I was still stuck with GDScript.

**URLs to the documentation pages:**
https://docs.godotengine.org/en/stable/getting_started/step_by_step/scripting.html and https://docs.godotengine.org/en/stable/getting_started/step_by_step/scripting_continued.html, if not everywhere.

**Comment by 31** [comment] 2021-03-28 16:48
This repros for me in `stable`, d8731526. Switching to `3.2` or `3.3` (at the bottom-left) makes the buttons work for me:
https://docs.godotengine.org/en/3.2/getting_started/step_by_step/scripting.html
https://docs.godotengine.org/en/3.2/getting_started/step_by_step/scripting_continued.html

(`stable` is based on `3.2`, so I'd guess it'll start working when the next build goes live.)

**Comment by Calinou** [comment] 2021-03-28 17:14
This is likely caused by https://github.com/readthedocs/readthedocs-sphinx-search/issues/82.

**Comment by 31** [comment] 2021-03-28 17:49
It looks like that broke the style, although the buttons do work (3.2):

![image](https://user-images.githubusercontent.com/331300/112762061-881e1680-8fc3-11eb-9aa7-bc92307dcb38.png)
https://docs.godotengine.org/en/3.2/getting_started/step_by_step/scripting.html

---

`stable` https://docs.godotengine.org/en/stable/getting_started/step_by_step/scripting.html is still the old d8731526 build for me.

I think things were ok in 3.2/3.3 before the most recent change, maybe all we needed was `stable` to catch up?

**Comment by 31** [comment] 2021-03-28 18:07
My bad! I had to do a forced refresh. Now the buttons now look normal on `3.2`/`3.3` for me.

**Comment by 31** [comment] 2021-03-28 18:44
`stable`, `3.2`, and `3.3` are now all working for me. 🎉

**Comment by Calinou** [comment] 2021-03-28 18:52
Closing per @31's comment. If it still doesn't work on your end, make sure to clear your browser's cache by using <kbd>Ctrl + F5</kbd> to reload the page.

**Closed by Calinou** 2021-03-28 18:52 UTC
Labels: bug
