### ISSUE TITLE
Documentation in tutorial clamp args inaccurate

### ISSUE THREAD

**Issue by soliforte** [godotengine/godot-docs#7958] opened 2023-09-19 04:42 UTC
**Your Godot version:**
4.1

**Issue description:**
In the tutorial, this line of code appears to be inaccurate:
`position = position.clamp(Vector2.ZERO, screen_size)`

Throws the error: Invalid type in function 'clamp' in base 'Vector2'. Cannot convert argument 2 from Rect2 to Vector2.

Issue was rectified by using screen_size.size.

**URL to the documentation page:**

https://docs.godotengine.org/en/stable/getting_started/first_2d_game/03.coding_the_player.html

If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

**Comment by AThousandShips** [comment] 2023-09-20 09:21
Please make sure you have copied the instructions correctly, you seem to have copied this part wrong and missed the `size` part:
```gdscript
func _ready():
    screen_size = get_viewport_rect().size
```
Because otherwise the value of `screen_size` is in fact a `Vector2`.

**Comment by AThousandShips** [comment] 2023-09-22 08:31
Closing as not a bug, if you have any other questions please reply here

**Closed by AThousandShips** 2023-09-22 08:31 UTC
