### ISSUE TITLE
iOS: Documentation Outliner Unusable in 4.1 Version

### ISSUE THREAD

**Issue by hmturnbull** [godotengine/godot-docs#8389] opened 2023-11-03 22:45 UTC
**Issue description:**
Around a week or two ago, the links in the `4.0` documentation's outline lost all functionality on iOS.  They won't expand, and I can't get to any of the pages in the docs without using the searchbox.

https://github.com/godotengine/godot-docs/assets/52052397/8c71e8b9-3d08-4486-a564-921e4c980a9e

- Note that whenever the focus changes to a different section, I'm tapping on it in an attempt to either expand it or go to its page.

As you can see, there's currently no way to browse the docs on iOS.

I'm using Firefox, but I've tried it on Safari as well; neither browser works.

This appears to be a problem in the `Godot 4.1` docs specifically; the `4.0` docs and earlier work as expected, as do the `4.2` (`latest`) docs.

**Comment by Calinou** [comment] 2023-11-10 10:30
> This appears to be a problem in the Godot 4.1 docs specifically; the 4.0 docs and earlier work as expected, as do the 4.2 (latest) docs.

The issue title mentions 4.0 is broken, but this part says 4.1 is broken. Which one is actually broken (is it both)?

**Comment by hmturnbull** [comment] 2023-11-10 18:39
> The issue title mentions 4.0 is broken, but this part says 4.1 is broken. Which one is actually broken (is it both)?

Oh.  Sorry.  That was a typo.  It was `4.1` that's broken; I didn't even realize I'd typed `4.0` until you pointed it out.

**Comment by YuriSizov** [comment] 2023-11-10 19:06
Thanks for the report, this is a duplicate of https://github.com/godotengine/godot-docs/issues/8351 which is fixed by https://github.com/godotengine/godot-docs/pull/8334. The fix is already available in the "latest" branch of the documentation, and the 4.1 version will be updated soon.

**Closed by YuriSizov** 2023-11-10 19:06 UTC
Labels: bug, content:website
