### ISSUE TITLE
Panel Class Properties need explanations

### ISSUE THREAD

**Issue by seedback** [godotengine/godot-docs#2699] opened 2019-08-12 16:59 UTC
As is, the [Panel Class's docs](https://docs.godotengine.org/en/3.1/classes/class_panel.html) have no explanation for what the three properties; _panel_, _panelf_ and _panelnc_, do or are used for.

**Comment by akien-mga** [comment] 2019-08-13 10:50
Duplicate of godotengine/godot#28639.

**Closed by akien-mga** 2019-08-13 10:50 UTC
