### ISSUE TITLE
The Godot Docs are using incorrect/outdated version of the connect function.

### ISSUE THREAD

**Issue by bytrofgodot** [godotengine/godot-docs#9592] opened 2024-07-11 09:04 UTC
**Your Godot version:**
4.2.2 stable.
**Issue description:**
when I use the code from the docs in the back to the lobby section to get the client id I get this error:
Invalid argument for "connect()" function: argument 2 should be "Callable" but is "res://server/server.gd".
Cannot pass a value of type "String" as "int".
Invalid argument for "connect()" function: argument 3 should be "int" but is "String".
**URL to the documentation page:**
https://docs.godotengine.org/en/3.4/tutorials/networking/high_level_multiplayer.html
If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

**Comment by AThousandShips** [comment] 2024-07-11 09:12
This is because you're on the 3.4 version of the docs, you should open the 4.2 version instead:
https://docs.godotengine.org/en/stable/tutorials/networking/high_level_multiplayer.html

Closing as this is not a bug

**Closed by AThousandShips** 2024-07-11 09:12 UTC
Labels: bug
