### ISSUE TITLE
Confusing section in Squash the Creeps tutorial

### ISSUE THREAD

**Issue by Rotaerk** [godotengine/godot-docs#5862] opened 2022-06-08 05:32 UTC
In the [Animating the Mobs](https://docs.godotengine.org/en/stable/getting_started/first_3d_game/09.adding_animations.html#animating-the-mobs) section of the animation page, the wording seems off and is confusing.

By the time you reach this point, the player is animated, and the mob is not.  This section indicates to:

> Open the Mob scene, select the animation player node and open the float animation. Next, click on Animation -> Copy. Then Open Player.tscn and open its animation player. Click Animation -> Paste. That's it; all monsters will now play the float animation.

It's backwards:  It should say to open the Player.tscn and copy from there, then paste into Mob.tscn.  it might also be helpful to mention that an Animation Player needs to be added to the Mob scene in the first place.

**Comment by mr-roboot-digital** [comment] 2022-06-08 11:31
Ok. You are helping the mob, right?
You said that the problem is mob is not animating because nothing pasted there.

**Comment by mr-roboot-digital** [comment] 2022-06-08 11:33
... Copy. Then Open Player.tscn and open its animation player. Click Animation -> Paste. 

Open Mob.tscn and open its animation player. Click Animation -> Paste.

**Comment by Rotaerk** [comment] 2022-06-08 21:07
I'm not sure I understand the question, but to try to clarify:  By the time you reach this section of the tutorial, your Player is already animated, but your Mob is not.  The instructions of this section indicate to copy the animation *into* the Player *from* the Mob, which doesn't make sense.  It's backwards.

**Comment by mr-roboot-digital** [comment] 2022-06-09 08:23
**ok.**

**Comment by nisc586** [comment] 2022-06-25 09:12
Hi,
I recently did the Squash the Creeps tutorial and came across the same issue. I am going to create a pull request to resolve this bug.

**Comment by jynus** [comment] 2022-07-24 17:21
Duplicate of #5913 , which was already patched and merged (current tutorial shows the fixed wording).

**Closed** 2022-07-24 17:41 UTC
Labels: bug
