### ISSUE TITLE
Better resources for the documentation

### ISSUE THREAD

**Issue by djrm** [godotengine/godot-docs#191] opened 2016-06-29 22:26 UTC
Currently the documentation has only a monolithic /img folder which contains all the images used in the docs, my suggestion is make /img a folder to store common images that can be accessed by every page, then every page can include its own resources in its page img folder

the img folder can have an structure like
- img
  - editor
  - diagrams
  - etc

here is a proposal for the editor folder
![screenshot from 2016-06-29 17-25-07](https://cloud.githubusercontent.com/assets/1103897/16470872/79fa9f84-3e1e-11e6-8782-c38cfaf73f7e.png)

as you can see it contains general elements that can be used by any page.

**Comment by pwab** [comment] 2017-07-17 10:55
Possible duplicate of #23

**Comment by mhilbrunner** [comment] 2018-01-05 19:55
Closing as duplicate of #23. Also there are per-folder `img/` folders now for the docs, at least. :)

**Closed by mhilbrunner** 2018-01-05 19:55 UTC
