### ISSUE TITLE
Need tutorial make game with only C++ module

### ISSUE THREAD

**Issue by kienvn** [godotengine/godot-docs#4789] opened 2021-03-28 16:01 UTC
**Your Godot version:**
3.2
**Issue description:**
I cant find docs or demo about make game by only C++ module without GDNative.
Can you write demo or tutorial how to do this?
**URL to the documentation page (if already existing):**

**Comment by Calinou** [comment] 2021-03-28 16:29
Duplicate of https://github.com/godotengine/godot-docs/issues/140.

That said, we recommend using GDScript or C# and using C++ only where you actually need it – that is, for performance-critical code or integrating third-party libraries.

**Closed by Calinou** 2021-03-28 16:29 UTC
Labels: enhancement
