### ISSUE TITLE
Documentation page for files and directories that should be ignored

### ISSUE THREAD

**Issue by ivanskodje** [godotengine/godot-docs#1360] opened 2018-04-13 03:47 UTC
If you currently search for keywords such as "gitignore", you get zero results.
If you search for keywords such as "git", you get many result. (I have not found any page that contains a list of folders or files that should be ignored.

I would suggest we add a page dedicated to each version control system, such as Git - and add a default .gitignore snippet of files and folders that should be ignored.

May be relevant to https://github.com/godotengine/godot-docs/issues/935, but I was unable to find anything based on that issue.

**Comment by ivanskodje** [comment] 2018-04-13 03:47
On gitignore.io, you can search for "Godot" and get the following defaults;

```
### Godot ###
.import/
.mono/
export_presets.cfg
```

**Comment by Calinou** [comment] 2020-04-20 08:56
Duplicate of #935.

**Closed by Calinou** 2020-04-20 08:56 UTC
Labels: enhancement
