### ISSUE TITLE
Text in methods table is squished on mobile

### ISSUE THREAD

**Issue by JorensM** [godotengine/godot-docs#8638] opened 2023-12-17 09:15 UTC
**Your Godot version:**

4.x

**Issue description:**

On API pages on mobile, the table that shows a list of a class's methods, the method name is very squished and unreadable.

![Screenshot_20231217-110942_Chrome](https://github.com/godotengine/godot-docs/assets/17122123/84942d31-629a-465c-b970-e65d00459f04)

Workaround is to view desktop version or switch to portrait mode.

**URL to the documentation page:**

Any page that has a table of methods, such as https://docs.godotengine.org/en/stable/classes/class_node.html 

If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

**Comment by AThousandShips** [comment] 2023-12-17 10:55
Duplicate of https://github.com/godotengine/godot-docs/issues/7504

**Closed by AThousandShips** 2023-12-17 10:55 UTC
Labels: bug
