### ISSUE TITLE
TileMap `fr/stable` vs  `en/stable` 

### ISSUE THREAD

**Issue by jaune** [godotengine/godot-docs#7705] opened 2023-07-21 08:14 UTC
**Your Godot version:** stable

**Issue description:**
TileMap `fr/stable` is not in sync with the `en/stable` version.

**URL to the documentation page:**
https://docs.godotengine.org/fr/stable/classes/class_tilemap.html 
https://docs.godotengine.org/en/stable/classes/class_tilemap.html

**Comment by AThousandShips** [comment] 2023-07-21 08:19
* Duplicate of: #7233

Thank you for reporting, consolidating in that issue, please search before opening a new one in the future

**Closed** 2023-07-21 08:19 UTC
Labels: bug
