### ISSUE TITLE
Three quotes is not a comment

### ISSUE THREAD

**Issue by genete** [godotengine/godot-docs#89] opened 2016-03-13 07:58 UTC
See: 
http://docs.godotengine.org/en/latest/reference/gdscript.html#comments

Now place:
""" Everything on these
lines is considered
a comment """

It delivers the following error:
Unexpected token. Constant:

**Comment by akien-mga** [comment] 2016-03-13 09:37
That's actually an engine bug more than a documentation bug: https://github.com/godotengine/godot/issues/1320 :)

Multiline comments work fine in functions, but in the global scope there seems to be some quirks.

**Comment by akien-mga** [comment] 2016-07-15 08:22
Closing as duplicate of #1320.

**Comment by akien-mga** [comment] 2016-07-15 08:23
Oops, I omitted that this is the docs repo. I guess the docs should be fixed until the above bug is fixed too.

**Closed** 2016-07-15 08:27 UTC
