### ISSUE TITLE
Links to more (learning) material

### ISSUE THREAD

**Issue by rolfpancake** [godotengine/godot-docs#21] opened 2016-02-25 11:44 UTC
When going through the tutorials there should be links for further reading.
At least a link to [awesome godot](https://github.com/Calinou/awesome-godot) (which is a great resource), would be a nice hint for every beginner.

**Comment by akien-mga** [comment] 2017-04-23 12:16
Closing as duplicate of the (later) #229 which has a slightly broader scope.

**Closed by akien-mga** 2017-04-23 12:16 UTC
