### ISSUE TITLE
the skeletonIK method's name is confusing and missing correct description

### ISSUE THREAD

**Issue by snougo** [godotengine/godot-docs#4607] opened 2021-01-30 18:12 UTC
**Your Godot version:**
3.2.4 RC1

**Issue description:**
right now the description of skeletonIK method is missing in documentation and skeletonIK method's name does not match its actual function, like start(), stop() etc.

the link of demo in documentation about how to use IK is useless because it doesn't use skeletonIK node instead of using a custom node

like metioned above, I think right now the biggest problem is missing the description about how to correctly enable IK and disable IK in script, because that's what I've experienced.

here is code
![Screen Shot 2021-01-31 at 01 05 20](https://user-images.githubusercontent.com/64188282/106362916-69532900-6360-11eb-8198-12864d53d0eb.png)

you can see the start() method need to be called every frame to update IK instead of just being called once, also you can see that you can't just simply call stop() method to disable IK, you have to call skeleton methodn clear_bones_global_pose_override() to clear override after calling stop()

there is a issue report about stop() method in https://github.com/godotengine/godot/issues/40384

I also find another issue about is_running(), it always return false whatever IK is enabled or not, I will open a new isssue report after this

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/classes/class_skeletonik.html

**Comment by smix8** [comment] 2021-04-20 15:23
Some of the described behavior was caused by bugs, some due to confusing function naming and lack of documentation.

SkeletonIK will only see small fixes but not large changes in Godot 3.x cause IK is completely reworked for Godot 4.x for both 2D and 3D. This doesn't mean we can't at least document the current caveeats in Godot 3.x to warn users.

SkeletonIK documentation PR:
https://github.com/godotengine/godot/pull/47938
Fix to `SkeletonIK.stop()` function only disabling process mode but not removing the applied IK transforms.
https://github.com/godotengine/godot/pull/47933
Fix to `Skeleton.clear_bones_global_pose_override()` not clearing persistent overrides.
https://github.com/godotengine/godot/pull/47923

**Comment by skyace65** [comment] 2022-01-09 03:29
@Calinou this issue was fixed by smix8's PR and can be closed. Wasn't sure if I needed to tag you or not for someone to see this. If not then sorry.

**Closed** 2022-01-09 14:43 UTC
Labels: bug
