### ISSUE TITLE
Link to C# on Godot API page is broken

### ISSUE THREAD

**Issue by vnen** [godotengine/godot-docs#947] opened 2018-01-05 03:54 UTC
It's a big no-no to use a hash (`#`) on a URL since it has special meaning. It should be replaced by a encoded value (`%23`). I don't know if this can be fixed in the `makerst.py` script or if it's an issue with RTD/Sphinx generation.

For reference this is the current link: http://docs.godotengine.org/en/latest/classes/class_@c#.html

This is the link that works: http://docs.godotengine.org/en/latest/classes/class_@c%23.html

**Comment by NullConstant** [comment] 2018-01-05 07:43
Alternatively, use `CSharp` rather than `C#`.

**Comment by neikeq** [comment] 2018-01-05 13:41
The problem is that this reference page is automatically generated from the ScriptLanguage name. If we were to change it, that would mean the editor would display CSharp when choosing the language for a new script, and that looks kind of bad.
BTW, this page is empty and I don't see it ever having anything, so maybe just get rid of it when empty.

**Comment by mhilbrunner** [comment] 2018-01-05 19:07
Should be hidden then.

**Comment by Calinou** [comment] 2020-07-30 09:04
`@C#` was removed from the documentation in https://github.com/godotengine/godot/pull/39622, so this should be fixed once the class reference is synchronized in the online version.

**Comment by akien-mga** [comment] 2020-07-30 09:10
Indeed, we can close it already.

**Closed by akien-mga** 2020-07-30 09:10 UTC
Labels: bug
