### ISSUE TITLE
Document the debugger

### ISSUE THREAD

**Issue by ZX-WT** [godotengine/godot-docs#298] opened 2016-11-08 14:45 UTC
I would like to document the debugger, just realize the debugger is not mentioned in the documentation, but I don't really use the debugger very often, I just started using it sometime ago and that's why I knew that the debugger part is missing. I am surprised that such fundamental feature has been left out for such a long time.

What I plan to do is by simply write a few lines about each section of the debugger,errors, remote inspector, profiler etc. I think that having short documentation about the debugger is better than nothing.

This could be done in a short time(I probably need to learn the syntax again, it was way too long that I committed a doc page), the problem is that I don't know what exactly these tools offer, could anyone offer some help?

**Comment by pwab** [comment] 2018-01-08 21:21
Are you still interested in contributing such a page for the docs? Would be awesome to have an overview of the tools/possibilities when v3 is shipped.

This page could:
- [ ] explain how to work with **errors** in general (stacktrace and such)
- [ ] show the use of the **debugger**
- [ ] show the use of the **profiler**
- [ ] show the use of **monitoring**
- [ ] show how to **remote debug** (see #173)
- [ ] explain **why** there is **no exception handling** (this could prevent questions like [this](https://godotengine.org/qa/6343/there-catch-exception-gdscript-instead-running-the-debugger))
- [ ] explain how to **log** exceptions ([see reference question](https://godotengine.org/qa/22116/unhandled-error-gdscript-after-release))

**Comment by ZX-WT** [comment] 2018-01-09 08:30
I would like to work on it but before that I need to understand the new debugger. The showing part should not be a difficult task for me but for the explaining part, I think it is better for a more experienced user to write it.

**Comment by mhilbrunner** [comment] 2018-03-13 18:30
Closing as duplicate of https://github.com/godotengine/godot-docs/issues/368 for now.

**Closed by mhilbrunner** 2018-03-13 18:30 UTC
